const vocabList = [
    // --- Level A1: Existing ---
    { id: 101, level: 'A1', category: 'Greeting', thai: "สวัสดี", transliteration: "Sawatdee", german: "Hallo", english: "Hello" },
    { id: 102, level: 'A1', category: 'Greeting', thai: "ลาก่อน", transliteration: "La gon", german: "Tschüss", english: "Goodbye" },
    { id: 103, level: 'A1', category: 'Basics', thai: "ใช่", transliteration: "Chai", german: "Ja", english: "Yes" },
    { id: 104, level: 'A1', category: 'Basics', thai: "ไม่", transliteration: "Mai", german: "Nein", english: "No" },
    { id: 105, level: 'A1', category: 'Basics', thai: "ขอบคุณ", transliteration: "Khop khun", german: "Danke", english: "Thank you" },
    { id: 106, level: 'A1', category: 'Basics', thai: "ขอโทษ", transliteration: "Khor thot", german: "Entschuldigung", english: "Sorry" },
    { id: 107, level: 'A1', category: 'Pronoun', thai: "ผม", transliteration: "Phom", german: "Ich (männlich)", english: "I (male)" },
    { id: 108, level: 'A1', category: 'Pronoun', thai: "ฉัน", transliteration: "Chan", german: "Ich (weiblich)", english: "I (female)" },
    { id: 109, level: 'A1', category: 'Pronoun', thai: "คุณ", transliteration: "Khun", german: "Du / Sie", english: "You" },
    { id: 110, level: 'A1', category: 'Question', thai: "อะไร", transliteration: "Arai", german: "Was", english: "What" },
    { id: 111, level: 'A1', category: 'Question', thai: "ที่ไหน", transliteration: "Theenai", german: "Wo", english: "Where" },
    { id: 112, level: 'A1', category: 'Question', thai: "เมื่อไหร่", transliteration: "Muearai", german: "Wann", english: "When" },
    { id: 113, level: 'A1', category: 'Question', thai: "ทำไม", transliteration: "Thammai", german: "Warum", english: "Why" },
    { id: 114, level: 'A1', category: 'Question', thai: "อย่างไร", transliteration: "Yangrai", german: "Wie", english: "How" },
    { id: 115, level: 'A1', category: 'Numbers', thai: "หนึ่ง", transliteration: "Nueng", german: "Eins", english: "One" },
    { id: 116, level: 'A1', category: 'Numbers', thai: "สอง", transliteration: "Song", german: "Zwei", english: "Two" },
    { id: 117, level: 'A1', category: 'Numbers', thai: "สาม", transliteration: "Sam", german: "Drei", english: "Three" },
    { id: 118, level: 'A1', category: 'Numbers', thai: "สี่", transliteration: "Si", german: "Vier", english: "Four" },
    { id: 119, level: 'A1', category: 'Numbers', thai: "ห้า", transliteration: "Ha", german: "Fünf", english: "Five" },
    { id: 120, level: 'A1', category: 'Family', thai: "พ่อ", transliteration: "Phor", german: "Vater", english: "Father" },
    { id: 121, level: 'A1', category: 'Family', thai: "แม่", transliteration: "Mae", german: "Mutter", english: "Mother" },
    { id: 122, level: 'A1', category: 'Verbs', thai: "กิน", transliteration: "Kin", german: "Essen", english: "Eat" },
    { id: 123, level: 'A1', category: 'Verbs', thai: "ดื่ม", transliteration: "Deum", german: "Trinken", english: "Drink" },
    { id: 124, level: 'A1', category: 'Verbs', thai: "ไป", transliteration: "Pai", german: "Gehen", english: "Go" },
    { id: 125, level: 'A1', category: 'Verbs', thai: "มา", transliteration: "Ma", german: "Kommen", english: "Come" },
    // --- Level A1: New Expansion (100+) ---
    // Pronouns & People
    { id: 1001, level: 'A1', category: 'People', thai: "เขา", transliteration: "Khao", german: "Er/Sie", english: "He/She" },
    { id: 1002, level: 'A1', category: 'People', thai: "เรา", transliteration: "Rao", german: "Wir", english: "We" },
    { id: 1003, level: 'A1', category: 'People', thai: "พวกเขา", transliteration: "Phuak-khao", german: "Sie (Plural)", english: "They" },
    { id: 1004, level: 'A1', category: 'People', thai: "น้องชาย", transliteration: "Nong-chai", german: "Jüngerer Bruder", english: "Younger Brother" },
    { id: 1005, level: 'A1', category: 'People', thai: "น้องสาว", transliteration: "Nong-sao", german: "Jüngere Schwester", english: "Younger Sister" },
    { id: 1006, level: 'A1', category: 'People', thai: "พี่ชาย", transliteration: "Pee-chai", german: "Älterer Bruder", english: "Older Brother" },
    { id: 1007, level: 'A1', category: 'People', thai: "พี่สาว", transliteration: "Pee-sao", german: "Ältere Schwester", english: "Older Sister" },
    { id: 1008, level: 'A1', category: 'People', thai: "ลูกชาย", transliteration: "Look-chai", german: "Sohn", english: "Son" },
    { id: 1009, level: 'A1', category: 'People', thai: "ลูกสาว", transliteration: "Look-sao", german: "Tochter", english: "Daughter" },
    { id: 1010, level: 'A1', category: 'People', thai: "เด็ก", transliteration: "Dek", german: "Kind", english: "Child" },
    { id: 1011, level: 'A1', category: 'People', thai: "ผู้ชาย", transliteration: "Phoo-chai", german: "Mann", english: "Man" },
    { id: 1012, level: 'A1', category: 'People', thai: "ผู้หญิง", transliteration: "Phoo-ying", german: "Frau", english: "Woman" },

    // Numbers (Extended)
    { id: 1013, level: 'A1', category: 'Numbers', thai: "ศูนย์", transliteration: "Soon", german: "Null", english: "Zero" },
    { id: 1014, level: 'A1', category: 'Numbers', thai: "หก", transliteration: "Hok", german: "Sechs", english: "Six" },
    { id: 1015, level: 'A1', category: 'Numbers', thai: "เจ็ด", transliteration: "Jet", german: "Sieben", english: "Seven" },
    { id: 1016, level: 'A1', category: 'Numbers', thai: "แปด", transliteration: "Paet", german: "Acht", english: "Eight" },
    { id: 1017, level: 'A1', category: 'Numbers', thai: "เก้า", transliteration: "Kao", german: "Neun", english: "Nine" },
    { id: 1018, level: 'A1', category: 'Numbers', thai: "สิบ", transliteration: "Sip", german: "Zehn", english: "Ten" },
    { id: 1019, level: 'A1', category: 'Numbers', thai: "สิบเอ็ด", transliteration: "Sip-et", german: "Elf", english: "Eleven" },
    { id: 1020, level: 'A1', category: 'Numbers', thai: "สิบสอง", transliteration: "Sip-song", german: "Zwölf", english: "Twelve" },
    { id: 1021, level: 'A1', category: 'Numbers', thai: "ยี่สิบ", transliteration: "Yee-sip", german: "Zwanzig", english: "Twenty" },
    { id: 1022, level: 'A1', category: 'Numbers', thai: "หนึ่งร้อย", transliteration: "Nueng-roi", german: "Hundert", english: "Hundred" },
    { id: 1023, level: 'A1', category: 'Numbers', thai: "หนึ่งพัน", transliteration: "Nueng-pan", german: "Tausend", english: "Thousand" },

    // Time (Basic)
    { id: 1024, level: 'A1', category: 'Time', thai: "วัน", transliteration: "Wan", german: "Tag", english: "Day" },
    { id: 1025, level: 'A1', category: 'Time', thai: "เดือน", transliteration: "Deuan", german: "Monat", english: "Month" },
    { id: 1026, level: 'A1', category: 'Time', thai: "ปี", transliteration: "Pee", german: "Jahr", english: "Year" },
    { id: 1027, level: 'A1', category: 'Time', thai: "ตอนเช้า", transliteration: "Ton-chao", german: "Morgen (Tageszeit)", english: "Morning" },
    { id: 1028, level: 'A1', category: 'Time', thai: "ตอนบ่าย", transliteration: "Ton-bai", german: "Nachmittag", english: "Afternoon" },
    { id: 1029, level: 'A1', category: 'Time', thai: "ตอนเย็น", transliteration: "Ton-yen", german: "Abend", english: "Evening" },
    { id: 1030, level: 'A1', category: 'Time', thai: "คืน", transliteration: "Keun", german: "Nacht", english: "Night" },
    { id: 1031, level: 'A1', category: 'Time', thai: "อาทิตย์", transliteration: "Ah-thit", german: "Woche", english: "Week" },
    { id: 1032, level: 'A1', category: 'Time', thai: "เวลา", transliteration: "Way-la", german: "Zeit", english: "Time" },
    { id: 1033, level: 'A1', category: 'Time', thai: "นาที", transliteration: "Na-thee", german: "Minute", english: "Minute" },
    { id: 1034, level: 'A1', category: 'Time', thai: "ชั่วโมง", transliteration: "Chua-mong", german: "Stunde", english: "Hour" },

    // Verbs (Action)
    { id: 1035, level: 'A1', category: 'Verbs', thai: "ดู", transliteration: "Doo", german: "Schauen/Sehen", english: "Look/See" },
    { id: 1036, level: 'A1', category: 'Verbs', thai: "ฟัง", transliteration: "Fang", german: "Zuhören", english: "Listen" },
    { id: 1037, level: 'A1', category: 'Verbs', thai: "พูด", transliteration: "Poot", german: "Sprechen", english: "Speak" },
    { id: 1038, level: 'A1', category: 'Verbs', thai: "อ่าน", transliteration: "Aan", german: "Lesen", english: "Read" },
    { id: 1039, level: 'A1', category: 'Verbs', thai: "เขียน", transliteration: "Khian", german: "Schreiben", english: "Write" },
    { id: 1040, level: 'A1', category: 'Verbs', thai: "เดิน", transliteration: "Doen", german: "Laufen/Gehen", english: "Walk" },
    { id: 1041, level: 'A1', category: 'Verbs', thai: "วิ่ง", transliteration: "Wing", german: "Rennen", english: "Run" },
    { id: 1042, level: 'A1', category: 'Verbs', thai: "นั่ง", transliteration: "Nang", german: "Sitzen", english: "Sit" },
    { id: 1043, level: 'A1', category: 'Verbs', thai: "ยืน", transliteration: "Yuen", german: "Stehen", english: "Stand" },
    { id: 1044, level: 'A1', category: 'Verbs', thai: "รัก", transliteration: "Rak", german: "Lieben", english: "Love" },
    { id: 1045, level: 'A1', category: 'Verbs', thai: "เกลียด", transliteration: "Kliat", german: "Hassen", english: "Hate" },
    { id: 1046, level: 'A1', category: 'Verbs', thai: "รู้", transliteration: "Roo", german: "Wissen", english: "Know" },
    { id: 1047, level: 'A1', category: 'Verbs', thai: "คิด", transliteration: "Khid", german: "Denken", english: "Think" },
    { id: 1048, level: 'A1', category: 'Verbs', thai: "ทำ", transliteration: "Tham", german: "Machen/Tun", english: "Do/Make" },
    { id: 1049, level: 'A1', category: 'Verbs', thai: "ให้", transliteration: "Hai", german: "Geben", english: "Give" },
    { id: 1050, level: 'A1', category: 'Verbs', thai: "รับ", transliteration: "Rap", german: "Nehmen/Bekommen", english: "Get/Receive" },

    // Adjectives (Basic)
    { id: 1051, level: 'A1', category: 'Adjectives', thai: "ใหญ่", transliteration: "Yai", german: "Groß", english: "Big" },
    { id: 1052, level: 'A1', category: 'Adjectives', thai: "เล็ก", transliteration: "Lek", german: "Klein", english: "Small" },
    { id: 1053, level: 'A1', category: 'Adjectives', thai: "ดี", transliteration: "Dee", german: "Gut", english: "Good" },
    { id: 1054, level: 'A1', category: 'Adjectives', thai: "ไม่ดี", transliteration: "Mai-dee", german: "Schlecht", english: "Bad" },
    { id: 1055, level: 'A1', category: 'Adjectives', thai: "สวย", transliteration: "Suay", german: "Schön", english: "Beautiful" },
    { id: 1056, level: 'A1', category: 'Adjectives', thai: "ใหม่", transliteration: "Mai", german: "Neu", english: "New" },
    { id: 1057, level: 'A1', category: 'Adjectives', thai: "เก่า", transliteration: "Kao", german: "Alt", english: "Old" },
    { id: 1058, level: 'A1', category: 'Adjectives', thai: "เร็ว", transliteration: "Reo", german: "Schnell", english: "Fast" },
    { id: 1059, level: 'A1', category: 'Adjectives', thai: "ช้า", transliteration: "Cha", german: "Langsam", english: "Slow" },
    { id: 1060, level: 'A1', category: 'Adjectives', thai: "ง่าย", transliteration: "Ngai", german: "Einfach", english: "Easy" },
    { id: 1061, level: 'A1', category: 'Adjectives', thai: "ยาก", transliteration: "Yak", german: "Schwer/Schwierig", english: "Difficult" },
    { id: 1062, level: 'A1', category: 'Adjectives', thai: "สูง", transliteration: "Soong", german: "Hoch", english: "High/Tall" },
    { id: 1063, level: 'A1', category: 'Adjectives', thai: "เตี้ย", transliteration: "Tia", german: "Klein (Körpergröße)", english: "Short (Height)" },
    { id: 1064, level: 'A1', category: 'Adjectives', thai: "ยาว", transliteration: "Yao", german: "Lang", english: "Long" },
    { id: 1065, level: 'A1', category: 'Adjectives', thai: "สั้น", transliteration: "San", german: "Kurz", english: "Short (Length)" },
    { id: 1066, level: 'A1', category: 'Adjectives', thai: "สะอาด", transliteration: "Sa-ard", german: "Sauber", english: "Clean" },
    { id: 1067, level: 'A1', category: 'Adjectives', thai: "สกปรก", transliteration: "Sok-ka-prok", german: "Schmutzig", english: "Dirty" },
    { id: 1068, level: 'A1', category: 'Adjectives', thai: "อ้วน", transliteration: "Uan", german: "Dick", english: "Fat" },
    { id: 1069, level: 'A1', category: 'Adjectives', thai: "ผอม", transliteration: "Phom", german: "Dünn", english: "Thin" },
    { id: 1070, level: 'A1', category: 'Adjectives', thai: "รวย", transliteration: "Ruay", german: "Reich", english: "Rich" },
    { id: 1071, level: 'A1', category: 'Adjectives', thai: "จน", transliteration: "Jon", german: "Arm", english: "Poor" },
    { id: 1072, level: 'A1', category: 'Adjectives', thai: "เต็ม", transliteration: "Tem", german: "Voll", english: "Full" },
    { id: 1073, level: 'A1', category: 'Adjectives', thai: "ว่าง", transliteration: "Wang", german: "Leer/Frei", english: "Empty/Free" },

    // Core Objects / Places
    { id: 1074, level: 'A1', category: 'Objects', thai: "น้ำ", transliteration: "Nam", german: "Wasser", english: "Water" },
    { id: 1075, level: 'A1', category: 'Objects', thai: "ข้าว", transliteration: "Khao", german: "Reis", english: "Rice" },
    { id: 1076, level: 'A1', category: 'Objects', thai: "โต๊ะ", transliteration: "To", german: "Tisch", english: "Table" },
    { id: 1077, level: 'A1', category: 'Objects', thai: "เก้าอี้", transliteration: "Kao-ee", german: "Stuhl", english: "Chair" },
    { id: 1078, level: 'A1', category: 'Objects', thai: "หนังสือ", transliteration: "Nang-sue", german: "Buch", english: "Book" },
    { id: 1079, level: 'A1', category: 'Objects', thai: "ปากกา", transliteration: "Pak-ka", german: "Stift", english: "Pen" },
    { id: 1080, level: 'A1', category: 'Places', thai: "ห้องน้ำ", transliteration: "Hong-nam", german: "Toilette", english: "Toilet/Bathroom" },
    { id: 1081, level: 'A1', category: 'Places', thai: "โรงเรียน", transliteration: "Rong-rian", german: "Schule", english: "School" },
    { id: 1082, level: 'A1', category: 'Places', thai: "ร้านอาหาร", transliteration: "Ran-a-han", german: "Restaurant", english: "Restaurant" },
    { id: 1083, level: 'A1', category: 'Places', thai: "ตลาด", transliteration: "Ta-lat", german: "Markt", english: "Market" },

    // Useful Connector Words / Particles
    { id: 1084, level: 'A1', category: 'Grammar', thai: "และ", transliteration: "Lae", german: "Und", english: "And" },
    { id: 1085, level: 'A1', category: 'Grammar', thai: "แต่", transliteration: "Tae", german: "Aber", english: "But" },
    { id: 1086, level: 'A1', category: 'Grammar', thai: "หรือ", transliteration: "Reue", german: "Oder", english: "Or" },
    { id: 1087, level: 'A1', category: 'Grammar', thai: "กับ", transliteration: "Kap", german: "Mit", english: "With" },
    { id: 1088, level: 'A1', category: 'Grammar', thai: "มาก", transliteration: "Mak", german: "Sehr/Viel", english: "Very/Much" },
    { id: 1089, level: 'A1', category: 'Grammar', thai: "นิดหน่อย", transliteration: "Nit-noi", german: "Ein bisschen", english: "A little" },
    { id: 1090, level: 'A1', category: 'Grammar', thai: "ใคร", transliteration: "Krai", german: "Wer", english: "Who" },
    { id: 1091, level: 'A1', category: 'Grammar', thai: "ของ", transliteration: "Khong", german: "Von (Besitz)", english: "Of/Belonging to" },
    { id: 1092, level: 'A1', category: 'Basics', thai: "ชื่อ", transliteration: "Chue", german: "Name", english: "Name" },
    { id: 1093, level: 'A1', category: 'Basics', thai: "สบายดี", transliteration: "Sabai-dee", german: "Es geht mir gut", english: "I am fine" },
    { id: 1094, level: 'A1', category: 'Basics', thai: "ไม่เป็นไร", transliteration: "Mai-pen-rai", german: "Kein Problem / Gerne", english: "No problem / You're welcome" },
    { id: 1095, level: 'A1', category: 'Basics', thai: "เข้าใจ", transliteration: "Khao-jai", german: "Verstehen", english: "Understand" },
    { id: 1096, level: 'A1', category: 'Basics', thai: "ไม่เข้าใจ", transliteration: "Mai-khao-jai", german: "Nicht verstehen", english: "Don't understand" },
    { id: 1097, level: 'A1', category: 'Basics', thai: "ช่วยเหลือ", transliteration: "Chuay-luea", german: "Helfen", english: "Help" },
    { id: 1098, level: 'A1', category: 'Basics', thai: "หยุด", transliteration: "Yut", german: "Stopp/Anhalten", english: "Stop" },
    { id: 1099, level: 'A1', category: 'Basics', thai: "เปิด", transliteration: "Poet", german: "Öffnen/Anschalten", english: "Open/Turn on" },
    { id: 1100, level: 'A1', category: 'Basics', thai: "ปิด", transliteration: "Pit", german: "Schließen/Ausschalten", english: "Close/Turn off" },

    // --- Level A2 (Elementary) ---
    { id: 201, level: 'A2', category: 'Time', thai: "วันนี้", transliteration: "Wan-nee", german: "Heute", english: "Today" },
    { id: 202, level: 'A2', category: 'Time', thai: "พรุ่งนี้", transliteration: "Prung-nee", german: "Morgen", english: "Tomorrow" },
    { id: 203, level: 'A2', category: 'Time', thai: "เมื่อวาน", transliteration: "Meua-wan", german: "Gestern", english: "Yesterday" },
    { id: 204, level: 'A2', category: 'Food', thai: "ข้าวผัด", transliteration: "Khao Pad", german: "Gebratener Reis", english: "Fried Rice" },
    { id: 205, level: 'A2', category: 'Food', thai: "เผ็ด", transliteration: "Phet", german: "Scharf", english: "Spicy" },
    { id: 206, level: 'A2', category: 'Places', thai: "โรงพยาบาล", transliteration: "Rong-phaya-ban", german: "Krankenhaus", english: "Hospital" },
    { id: 207, level: 'A2', category: 'Places', thai: "สนามบิน", transliteration: "Sanam-bin", german: "Flughafen", english: "Airport" },
    { id: 208, level: 'A2', category: 'Travel', thai: "ตั๋ว", transliteration: "Tua", german: "Ticket", english: "Ticket" },
    { id: 209, level: 'A2', category: 'Health', thai: "ป่วย", transliteration: "Puay", german: "Krank", english: "Sick" },
    { id: 210, level: 'A2', category: 'Verbs', thai: "ชอบ", transliteration: "Chop", german: "Mögen", english: "Like" },
    { id: 211, level: 'A2', category: 'Verbs', thai: "อยาก", transliteration: "Yak", german: "Wollen", english: "Want" },
    { id: 212, level: 'A2', category: 'Shopping', thai: "ราคา", transliteration: "Ra-kha", german: "Preis", english: "Price" },
    { id: 213, level: 'A2', category: 'Shopping', thai: "แพง", transliteration: "Phaeng", german: "Teuer", english: "Expensive" },
    { id: 214, level: 'A2', category: 'Shopping', thai: "ถูก", transliteration: "Thook", german: "Billig", english: "Cheap" },
    { id: 215, level: 'A2', category: 'Colors', thai: "สีแดง", transliteration: "Si Daeng", german: "Rot", english: "Red" },
    { id: 216, level: 'A2', category: 'Colors', thai: "สีน้ำเงิน", transliteration: "Si Nam-ngoen", german: "Blau", english: "Blue" },
    { id: 217, level: 'A2', category: 'Colors', thai: "สีขาว", transliteration: "Si Khao", german: "Weiß", english: "White" },
    { id: 218, level: 'A2', category: 'Colors', thai: "สีดำ", transliteration: "Si Dam", german: "Schwarz", english: "Black" },
    { id: 219, level: 'A2', category: 'Weather', thai: "ร้อน", transliteration: "Ron", german: "Heiß", english: "Hot" },
    { id: 220, level: 'A2', category: 'Weather', thai: "หนาว", transliteration: "Nao", german: "Kalt", english: "Cold" },

    // --- Level A2: New Expansion (100+) ---
    // Food & Dining
    { id: 2001, level: 'A2', category: 'Food', thai: "ก๋วยเตี๋ยว", transliteration: "Kuay-tiao", german: "Nudelsuppe", english: "Noodle Soup" },
    { id: 2002, level: 'A2', category: 'Food', thai: "ผัดไทย", transliteration: "Pad Thai", german: "Gebratene Nudeln (Pad Thai)", english: "Pad Thai" },
    { id: 2003, level: 'A2', category: 'Food', thai: "แกงเขียวหวาน", transliteration: "Kaeng Khiao Wan", german: "Grünes Curry", english: "Green Curry" },
    { id: 2004, level: 'A2', category: 'Food', thai: "ต้มยำกุ้ง", transliteration: "Tom Yam Kung", german: "Tom Yam Suppe (Garnelen)", english: "Tom Yam Kung" },
    { id: 2005, level: 'A2', category: 'Food', thai: "ส้มตำ", transliteration: "Som Tam", german: "Papayasalat", english: "Papaya Salad" },
    { id: 2006, level: 'A2', category: 'Food', thai: "ไก่ทอด", transliteration: "Gai Thod", german: "Frittiertes Hühnchen", english: "Fried Chicken" },
    { id: 2007, level: 'A2', category: 'Food', thai: "หมู", transliteration: "Moo", german: "Schwein", english: "Pork" },
    { id: 2008, level: 'A2', category: 'Food', thai: "ไก่", transliteration: "Gai", german: "Huhn", english: "Chicken" },
    { id: 2009, level: 'A2', category: 'Food', thai: "เนื้อวัว", transliteration: "Nuea Wua", german: "Rindfleisch", english: "Beef" },
    { id: 2010, level: 'A2', category: 'Food', thai: "ปลา", transliteration: "Pla", german: "Fisch", english: "Fish" },
    { id: 2011, level: 'A2', category: 'Food', thai: "กุ้ง", transliteration: "Kung", german: "Garnele", english: "Shrimp" },
    { id: 2012, level: 'A2', category: 'Food', thai: "ไข่", transliteration: "Khai", german: "Ei", english: "Egg" },
    { id: 2013, level: 'A2', category: 'Food', thai: "ผัก", transliteration: "Phak", german: "Gemüse", english: "Vegetable" },
    { id: 2014, level: 'A2', category: 'Food', thai: "ผลไม้", transliteration: "Pol-la-mai", german: "Obst", english: "Fruit" },
    { id: 2015, level: 'A2', category: 'Food', thai: "น้ำเปล่า", transliteration: "Nam Plao", german: "Stilles Wasser", english: "Plain Water" },
    { id: 2016, level: 'A2', category: 'Food', thai: "กาแฟ", transliteration: "Ka-fae", german: "Kaffee", english: "Coffee" },
    { id: 2017, level: 'A2', category: 'Food', thai: "ชา", transliteration: "Cha", german: "Tee", english: "Tea" },
    { id: 2018, level: 'A2', category: 'Food', thai: "นม", transliteration: "Nom", german: "Milch", english: "Milk" },
    { id: 2019, level: 'A2', category: 'Food', thai: "น้ำตาล", transliteration: "Nam-tan", german: "Zucker", english: "Sugar" },
    { id: 2020, level: 'A2', category: 'Food', thai: "เกลือ", transliteration: "Kluea", german: "Salz", english: "Salt" },
    { id: 2021, level: 'A2', category: 'Food', thai: "อร่อย", transliteration: "A-roi", german: "Lecker", english: "Delicious" },
    { id: 2022, level: 'A2', category: 'Food', thai: "หิวข้าว", transliteration: "Hiw Khao", german: "Hunger haben", english: "Hungry for rice/food" },
    { id: 2023, level: 'A2', category: 'Food', thai: "อิ่ม", transliteration: "Im", german: "Satt", english: "Full (stomach)" },
    { id: 2024, level: 'A2', category: 'Food', thai: "เก็บเงิน", transliteration: "Kep Ngoen", german: "Bezahlen (Rechnung bitte)", english: "Bill please" },

    // Places & Travel
    { id: 2025, level: 'A2', category: 'Places', thai: "โรงแรม", transliteration: "Rong-raem", german: "Hotel", english: "Hotel" },
    { id: 2026, level: 'A2', category: 'Places', thai: "สถานีตำรวจ", transliteration: "Sa-tha-nee Tam-ruat", german: "Polizeistation", english: "Police Station" },
    { id: 2027, level: 'A2', category: 'Places', thai: "ไปรษณีย์", transliteration: "Prai-sa-nee", german: "Post", english: "Post Office" },
    { id: 2028, level: 'A2', category: 'Places', thai: "ธนาคาร", transliteration: "Tha-na-khan", german: "Bank", english: "Bank" },
    { id: 2029, level: 'A2', category: 'Places', thai: "วัด", transliteration: "Wat", german: "Tempel", english: "Temple" },
    { id: 2030, level: 'A2', category: 'Places', thai: "ทะเล", transliteration: "Tha-lay", german: "Meer/Strand", english: "Sea/Beach" },
    { id: 2031, level: 'A2', category: 'Places', thai: "ภูเขา", transliteration: "Phoo-khao", german: "Berg", english: "Mountain" },
    { id: 2032, level: 'A2', category: 'Travel', thai: "เดินทาง", transliteration: "Doen-thang", german: "Reisen", english: "Travel" },
    { id: 2033, level: 'A2', category: 'Travel', thai: "กระเป๋าเดินทาง", transliteration: "Kra-pao Doen-thang", german: "Koffer", english: "Suitcase" },
    { id: 2034, level: 'A2', category: 'Travel', thai: "พาสปอร์ต", transliteration: "Passport", german: "Reisepass", english: "Passport" },
    { id: 2035, level: 'A2', category: 'Travel', thai: "วีซ่า", transliteration: "Visa", german: "Visum", english: "Visa" },
    { id: 2036, level: 'A2', category: 'Travel', thai: "แผนที่", transliteration: "Phaen-thee", german: "Karte (Landkarte)", english: "Map" },
    { id: 2037, level: 'A2', category: 'Travel', thai: "หลงทาง", transliteration: "Long-thang", german: "Verlaufen (Weg)", english: "Lost" },
    { id: 2038, level: 'A2', category: 'Travel', thai: "เลี้ยวซ้าย", transliteration: "Liao Sai", german: "Links abbiegen", english: "Turn Left" },
    { id: 2039, level: 'A2', category: 'Travel', thai: "เลี้ยวขวา", transliteration: "Liao Khwa", german: "Rechts abbiegen", english: "Turn Right" },
    { id: 2040, level: 'A2', category: 'Travel', thai: "ตรงไป", transliteration: "Trong Pai", german: "Geradeaus", english: "Go Straight" },
    { id: 2041, level: 'A2', category: 'Travel', thai: "ใกล้", transliteration: "Klai", german: "Nah", english: "Near" },
    { id: 2042, level: 'A2', category: 'Travel', thai: "ไกล", transliteration: "Klai", german: "Weit", english: "Far" }, // Tone difference! Klâi vs Klai

    // Shopping & Clothing
    { id: 2043, level: 'A2', category: 'Shopping', thai: "ซื้อ", transliteration: "Sue", german: "Kaufen", english: "Buy" },
    { id: 2044, level: 'A2', category: 'Shopping', thai: "ขาย", transliteration: "Khai", german: "Verkaufen", english: "Sell" },
    { id: 2045, level: 'A2', category: 'Shopping', thai: "ลดราคา", transliteration: "Lot Ra-kha", german: "Rabatt/Reduzieren", english: "Discount" },
    { id: 2046, level: 'A2', category: 'Shopping', thai: "เท่าไหร่", transliteration: "Thao-rai", german: "Wie viel?", english: "How much?" },
    { id: 2047, level: 'A2', category: 'Shopping', thai: "เสื้อ", transliteration: "Suea", german: "Oberteil/Shirt", english: "Shirt" },
    { id: 2048, level: 'A2', category: 'Shopping', thai: "กางเกง", transliteration: "Kang-keng", german: "Hose", english: "Pants" },
    { id: 2049, level: 'A2', category: 'Shopping', thai: "รองเท้า", transliteration: "Rong-thao", german: "Schuhe", english: "Shoes" },
    { id: 2050, level: 'A2', category: 'Shopping', thai: "กระเป๋า", transliteration: "Kra-pao", german: "Tasche", english: "Bag" },
    { id: 2051, level: 'A2', category: 'Shopping', thai: "หมวก", transliteration: "Muak", german: "Hut/Mütze", english: "Hat" },
    { id: 2052, level: 'A2', category: 'Shopping', thai: "แว่นตา", transliteration: "Waen-ta", german: "Brille", english: "Glasses" },

    // Colors (Extended)
    { id: 2053, level: 'A2', category: 'Colors', thai: "สีเขียว", transliteration: "Si Khiao", german: "Grün", english: "Green" },
    { id: 2054, level: 'A2', category: 'Colors', thai: "สีเหลือง", transliteration: "Si Lueang", german: "Gelb", english: "Yellow" },
    { id: 2055, level: 'A2', category: 'Colors', thai: "สีส้ม", transliteration: "Si Som", german: "Orange", english: "Orange" },
    { id: 2056, level: 'A2', category: 'Colors', thai: "สีชมพู", transliteration: "Si Chom-phu", german: "Rosa", english: "Pink" },
    { id: 2057, level: 'A2', category: 'Colors', thai: "สีม่วง", transliteration: "Si Muang", german: "Lila", english: "Purple" },
    { id: 2058, level: 'A2', category: 'Colors', thai: "สีน้ำตาล", transliteration: "Si Nam-tan", german: "Braun", english: "Brown" },
    { id: 2059, level: 'A2', category: 'Colors', thai: "สีเทา", transliteration: "Si Thao", german: "Grau", english: "Grey" },

    // Weather & Nature
    { id: 2060, level: 'A2', category: 'Weather', thai: "ฝนตก", transliteration: "Fon Tok", german: "Es regnet", english: "Rain" },
    { id: 2061, level: 'A2', category: 'Weather', thai: "แดดออก", transliteration: "Daet Ok", german: "Sonnig", english: "Sunny" },
    { id: 2062, level: 'A2', category: 'Weather', thai: "ลมแรง", transliteration: "Lom Raeng", german: "Windig", english: "Windy" },
    { id: 2063, level: 'A2', category: 'Weather', thai: "หิมะ", transliteration: "Hi-ma", german: "Schnee", english: "Snow" },
    { id: 2064, level: 'A2', category: 'Weather', thai: "พระอาทิตย์", transliteration: "Phra-a-thit", german: "Sonne", english: "Sun" },
    { id: 2065, level: 'A2', category: 'Weather', thai: "พระจันทร์", transliteration: "Phra-jan", german: "Mond", english: "Moon" },
    { id: 2066, level: 'A2', category: 'Weather', thai: "ดาว", transliteration: "Dao", german: "Stern", english: "Star" },
    { id: 2067, level: 'A2', category: 'Weather', thai: "ท้องฟ้า", transliteration: "Thong-fah", german: "Himmel", english: "Sky" },

    // Health
    { id: 2068, level: 'A2', category: 'Health', thai: "หมอ", transliteration: "Mor", german: "Arzt", english: "Doctor" },
    { id: 2069, level: 'A2', category: 'Health', thai: "พยาบาล", transliteration: "Pha-ya-ban", german: "Krankenschwester", english: "Nurse" },
    { id: 2070, level: 'A2', category: 'Health', thai: "ยา", transliteration: "Ya", german: "Medizin", english: "Medicine" },
    { id: 2071, level: 'A2', category: 'Health', thai: "ปวดหัว", transliteration: "Puad Hua", german: "Kopfschmerzen", english: "Headache" },
    { id: 2072, level: 'A2', category: 'Health', thai: "ปวดท้อง", transliteration: "Puad Thong", german: "Bauchschmerzen", english: "Stomachache" },
    { id: 2073, level: 'A2', category: 'Health', thai: "เป็นไข้", transliteration: "Pen Khai", german: "Fieber haben", english: "Have a fever" },
    { id: 2074, level: 'A2', category: 'Health', thai: "เจ็บ", transliteration: "Jep", german: "Schmerzen/Weh tun", english: "Hurt/Pain" },
    { id: 2075, level: 'A2', category: 'Health', thai: "เลือด", transliteration: "Lueat", german: "Blut", english: "Blood" },

    // Verbs (Abstract/Modal)
    { id: 2076, level: 'A2', category: 'Verbs', thai: "ต้อง", transliteration: "Tong", german: "Müssen", english: "Must" },
    { id: 2077, level: 'A2', category: 'Verbs', thai: "อาจจะ", transliteration: "Aat-ja", german: "Vielleicht (könnte)", english: "Might" },
    { id: 2078, level: 'A2', category: 'Verbs', thai: "ได้", transliteration: "Dai", german: "Können/Dürfen (am Ende)", english: "Can/Able" },
    { id: 2079, level: 'A2', category: 'Verbs', thai: "เคย", transliteration: "Khoei", german: "Schon mal gemacht haben", english: "Ever/Used to" },
    { id: 2080, level: 'A2', category: 'Verbs', thai: "รอ", transliteration: "Ror", german: "Warten", english: "Wait" },
    { id: 2081, level: 'A2', category: 'Verbs', thai: "ช่วย", transliteration: "Chuay", german: "Helfen (Bitte)", english: "Help/Please" },
    { id: 2082, level: 'A2', category: 'Verbs', thai: "ลืม", transliteration: "Luem", german: "Vergessen", english: "Forget" },
    { id: 2083, level: 'A2', category: 'Verbs', thai: "จำ", transliteration: "Jam", german: "Erinnern", english: "Remember" },
    { id: 2084, level: 'A2', category: 'Verbs', thai: "เรียนรู้", transliteration: "Rian-roo", german: "Erlernen", english: "Learn" },
    { id: 2085, level: 'A2', category: 'Verbs', thai: "สอน", transliteration: "Sorn", german: "Lehren/Unterrichten", english: "Teach" },
    { id: 2086, level: 'A2', category: 'Verbs', thai: "ถาม", transliteration: "Tham", german: "Fragen", english: "Ask" },
    { id: 2087, level: 'A2', category: 'Verbs', thai: "ตอบ", transliteration: "Top", german: "Antworten", english: "Answer" },

    // Time (Future/Past keywords)
    { id: 2088, level: 'A2', category: 'Time', thai: "จะ", transliteration: "Ja", german: "Werden (Zukunft)", english: "Will" },
    { id: 2089, level: 'A2', category: 'Time', thai: "กำลัง", transliteration: "Kam-lang", german: "Gerade tun (Verlauf)", english: "-ing (Progressive)" },
    { id: 2090, level: 'A2', category: 'Time', thai: "แล้ว", transliteration: "Laeo", german: "Schon/Bereits", english: "Already/Past tense particle" },
    { id: 2091, level: 'A2', category: 'Time', thai: "บ่อยๆ", transliteration: "Boi-boi", german: "Oft", english: "Often" },
    { id: 2092, level: 'A2', category: 'Time', thai: "บางครั้ง", transliteration: "Bang-khrang", german: "Manchmal", english: "Sometimes" },
    { id: 2093, level: 'A2', category: 'Time', thai: "ไม่เคย", transliteration: "Mai-khoei", german: "Niemals", english: "Never" },
    { id: 2094, level: 'A2', category: 'Time', thai: "ทุกวัน", transliteration: "Thook-wan", german: "Jeden Tag", english: "Every day" },

    // Prepositions
    { id: 2095, level: 'A2', category: 'Grammar', thai: "ใน", transliteration: "Nai", german: "In/Drinnen", english: "In" },
    { id: 2096, level: 'A2', category: 'Grammar', thai: "นอก", transliteration: "Nok", german: "Draußen", english: "Outside" },
    { id: 2097, level: 'A2', category: 'Grammar', thai: "บน", transliteration: "Bon", german: "Auf", english: "On" },
    { id: 2098, level: 'A2', category: 'Grammar', thai: "ใต้", transliteration: "Tai", german: "Unter", english: "Under" },
    { id: 2099, level: 'A2', category: 'Grammar', thai: "ข้างๆ", transliteration: "Khang-khang", german: "Neben", english: "Beside" },
    { id: 2100, level: 'A2', category: 'Grammar', thai: "ระหวาง", transliteration: "Ra-wang", german: "Zwischen", english: "Between" },

    // --- Daily Life (Alltag) ---
    { id: 301, level: 'Everyday', category: 'Objects', thai: "โทรศัพท์", transliteration: "Thor-a-sap", german: "Telefon", english: "Telephone" },
    { id: 302, level: 'Everyday', category: 'Objects', thai: "กุญแจ", transliteration: "Kun-jae", german: "Schlüssel", english: "Key" },
    { id: 303, level: 'Everyday', category: 'Objects', thai: "เงิน", transliteration: "Ngoen", german: "Geld", english: "Money" },
    { id: 304, level: 'Everyday', category: 'Activities', thai: "ทำงาน", transliteration: "Tham-ngan", german: "Arbeiten", english: "Work" },
    { id: 305, level: 'Everyday', category: 'Activities', thai: "เรียน", transliteration: "Rian", german: "Lernen", english: "Study/Learn" },
    { id: 306, level: 'Everyday', category: 'Activities', thai: "นอน", transliteration: "Non", german: "Schlafen", english: "Sleep" },
    { id: 307, level: 'Everyday', category: 'Transport', thai: "รถ", transliteration: "Rot", german: "Auto", english: "Car" },
    { id: 308, level: 'Everyday', category: 'Transport', thai: "รถเมล์", transliteration: "Rot-may", german: "Bus", english: "Bus" },
    { id: 309, level: 'Everyday', category: 'Transport', thai: "รถไฟ", transliteration: "Rot-fai", german: "Zug", english: "Train" },
    { id: 310, level: 'Everyday', category: 'Home', thai: "บ้าน", transliteration: "Baan", german: "Haus", english: "House" },
    { id: 311, level: 'Everyday', category: 'Home', thai: "ห้อง", transliteration: "Hong", german: "Zimmer", english: "Room" },
    { id: 312, level: 'Everyday', category: 'Social', thai: "เพื่อน", transliteration: "Peuan", german: "Freund", english: "Friend" },
    { id: 313, level: 'Everyday', category: 'Social', thai: "แฟน", transliteration: "Fan", german: "Freund/in (Partner)", english: "Boyfriend/Girlfriend" },
    { id: 314, level: 'Everyday', category: 'Feelings', thai: "มีความสุข", transliteration: "Mee kwahm sook", german: "Glücklich", english: "Happy" },
    { id: 315, level: 'Everyday', category: 'Feelings', thai: "เหนื่อย", transliteration: "Nuay", german: "Müde", english: "Tired" },
    { id: 316, level: 'Everyday', category: 'Feelings', thai: "หิว", transliteration: "Hiw", german: "Hungrig", english: "Hungry" },
    { id: 317, level: 'Everyday', category: 'Body', thai: "มือ", transliteration: "Meu", german: "Hand", english: "Hand" },
    { id: 318, level: 'Everyday', category: 'Body', thai: "หัว", transliteration: "Hua", german: "Kopf", english: "Head" },
    { id: 319, level: 'Everyday', category: 'Body', thai: "ตา", transliteration: "Taa", german: "Auge", english: "Eye" },
    { id: 320, level: 'Everyday', category: 'Body', thai: "ปาก", transliteration: "Paak", german: "Mund", english: "Mouth" },

    // --- Everyday: New Expansion (100+) ---
    // Work & Office
    { id: 3001, level: 'Everyday', category: 'Work', thai: "บริษัท", transliteration: "Bor-ri-sat", german: "Firma", english: "Company" },
    { id: 3002, level: 'Everyday', category: 'Work', thai: "ประชุม", transliteration: "Pra-choom", german: "Besprechung/Meeting", english: "Meeting" },
    { id: 3003, level: 'Everyday', category: 'Work', thai: "เจ้านาย", transliteration: "Jao-nai", german: "Chef", english: "Boss" },
    { id: 3004, level: 'Everyday', category: 'Work', thai: "ลูกน้อง", transliteration: "Look-nong", german: "Untergebener/Mitarbeiter", english: "Subordinate" },
    { id: 3005, level: 'Everyday', category: 'Work', thai: "เงินเดือน", transliteration: "Ngoen-deuan", german: "Gehalt", english: "Salary" },
    { id: 3006, level: 'Everyday', category: 'Work', thai: "ลาพักร้อน", transliteration: "La Phak-ron", german: "Urlaub (Arbeit)", english: "Vacation (Leave)" },
    { id: 3007, level: 'Everyday', category: 'Work', thai: "คอมพิวเตอร์", transliteration: "Computer", german: "Computer", english: "Computer" },
    { id: 3008, level: 'Everyday', category: 'Work', thai: "อีเมล", transliteration: "Email", german: "E-Mail", english: "Email" },
    { id: 3009, level: 'Everyday', category: 'Work', thai: "ลูกค้า", transliteration: "Look-kha", german: "Kunde", english: "Customer" },
    { id: 3010, level: 'Everyday', category: 'Work', thai: "สัญญา", transliteration: "San-ya", german: "Vertrag/Versprechen", english: "Contract/Promise" },
    { id: 3011, level: 'Everyday', category: 'Work', thai: "เอกสาร", transliteration: "Ek-ka-san", german: "Dokument", english: "Document" },
    { id: 3012, level: 'Everyday', category: 'Work', thai: "สัมภาษณ์", transliteration: "Sam-phat", german: "Interview", english: "Interview" },
    { id: 3013, level: 'Everyday', category: 'Work', thai: "ความสำเร็จ", transliteration: "Khwam-sam-ret", german: "Erfolg", english: "Success" },
    { id: 3014, level: 'Everyday', category: 'Work', thai: "ปัญหา", transliteration: "Pan-ha", german: "Problem", english: "Problem" },
    { id: 3015, level: 'Everyday', category: 'Work', thai: "แก้ปัญหา", transliteration: "Kae Pan-ha", german: "Problem lösen", english: "Solve Problem" },

    // Feelings & Emotions (Extended)
    { id: 3016, level: 'Everyday', category: 'Feelings', thai: "ตื่นเต้น", transliteration: "Tuen-ten", german: "Aufgeregt", english: "Excited" },
    { id: 3017, level: 'Everyday', category: 'Feelings', thai: "เบื่อ", transliteration: "Buea", german: "Gelangweilt", english: "Bored" },
    { id: 3018, level: 'Everyday', category: 'Feelings', thai: "กลัว", transliteration: "Klua", german: "Angst haben", english: "Scared" },
    { id: 3019, level: 'Everyday', category: 'Feelings', thai: "โกรธ", transliteration: "Krot", german: "Wütend", english: "Angry" },
    { id: 3020, level: 'Everyday', category: 'Feelings', thai: "อาย", transliteration: "Ai", german: "Schüchtern/Peinlich", english: "Shy/Embarrassed" },
    { id: 3021, level: 'Everyday', category: 'Feelings', thai: "เครียด", transliteration: "Khriat", german: "Gestresst", english: "Stressed" },
    { id: 3022, level: 'Everyday', category: 'Feelings', thai: "เหงา", transliteration: "Ngao", german: "Einsam", english: "Lonely" },
    { id: 3023, level: 'Everyday', category: 'Feelings', thai: "เสียใจ", transliteration: "Sia-jai", german: "Traurig/Tut mir leid", english: "Sad/Sorry" },
    { id: 3024, level: 'Everyday', category: 'Feelings', thai: "ดีใจ", transliteration: "Dee-jai", german: "Froh/Erfreut", english: "Glad" },
    { id: 3025, level: 'Everyday', category: 'Feelings', thai: "ตกใจ", transliteration: "Tok-jai", german: "Erschrocken/Überrascht", english: "Shocked" },
    { id: 3026, level: 'Everyday', category: 'Feelings', thai: "สับสน", transliteration: "Sap-son", german: "Verwirrt", english: "Confused" },
    { id: 3027, level: 'Everyday', category: 'Feelings', thai: "มั่นใจ", transliteration: "Man-jai", german: "Selbstsicher", english: "Confident" },
    { id: 3028, level: 'Everyday', category: 'Feelings', thai: "ภูมิใจ", transliteration: "Poom-jai", german: "Stolz", english: "Proud" },

    // Social & Hobbies
    { id: 3029, level: 'Everyday', category: 'Social', thai: "ปาร์ตี้", transliteration: "Party", german: "Party", english: "Party" },
    { id: 3030, level: 'Everyday', category: 'Social', thai: "นัด", transliteration: "Nat", german: "Verabredung/Termin", english: "Appointment/Date" },
    { id: 3031, level: 'Everyday', category: 'Social', thai: "เที่ยว", transliteration: "Thiao", german: "Ausgehen/Reisen", english: "Go out/Travel" },
    { id: 3032, level: 'Everyday', category: 'Social', thai: "ดูหนัง", transliteration: "Doo Nang", german: "Film schauen", english: "Watch Movie" },
    { id: 3033, level: 'Everyday', category: 'Social', thai: "ฟังเพลง", transliteration: "Fang Phleng", german: "Musik hören", english: "Listen to Music" },
    { id: 3034, level: 'Everyday', category: 'Social', thai: "ร้องเพลง", transliteration: "Rong Phleng", german: "Singen", english: "Sing" },
    { id: 3035, level: 'Everyday', category: 'Social', thai: "เต้น", transliteration: "Ten", german: "Tanzen", english: "Dance" },
    { id: 3036, level: 'Everyday', category: 'Social', thai: "เล่นกีฬา", transliteration: "Len Ki-la", german: "Sport machen", english: "Play Sports" },
    { id: 3037, level: 'Everyday', category: 'Social', thai: "ว่ายน้ำ", transliteration: "Wai-nam", german: "Schwimmen", english: "Swim" },
    { id: 3038, level: 'Everyday', category: 'Social', thai: "ถ่ายรูป", transliteration: "Thai Roop", german: "Fotos machen", english: "Take Photos" },
    { id: 3039, level: 'Everyday', category: 'Social', thai: "เล่นเกม", transliteration: "Len Game", german: "Spiele spielen", english: "Play Games" },
    { id: 3040, level: 'Everyday', category: 'Social', thai: "ของขวัญ", transliteration: "Khong-khwan", german: "Geschenk", english: "Gift" },
    { id: 3041, level: 'Everyday', category: 'Social', thai: "ฉลอง", transliteration: "Cha-long", german: "Feiern", english: "Celebrate" },

    // Home & Household
    { id: 3042, level: 'Everyday', category: 'Home', thai: "ทำความสะอาด", transliteration: "Tham-khwam-sa-ard", german: "Putzen", english: "Clean" },
    { id: 3043, level: 'Everyday', category: 'Home', thai: "ซักผ้า", transliteration: "Sak Pha", german: "Wäsche waschen", english: "Wash Clothes" },
    { id: 3044, level: 'Everyday', category: 'Home', thai: "ล้างจาน", transliteration: "Lang Jan", german: "Geschirr spülen", english: "Wash Dishes" },
    { id: 3045, level: 'Everyday', category: 'Home', thai: "ทำกับข้าว", transliteration: "Tham Kap-khao", german: "Kochen", english: "Cook" },
    { id: 3046, level: 'Everyday', category: 'Home', thai: "ตู้เย็น", transliteration: "Too-yen", german: "Kühlschrank", english: "Fridge" },
    { id: 3047, level: 'Everyday', category: 'Home', thai: "เตียง", transliteration: "Tiang", german: "Bett", english: "Bed" },
    { id: 3048, level: 'Everyday', category: 'Home', thai: "หมอน", transliteration: "Mon", german: "Kissen", english: "Pillow" },
    { id: 3049, level: 'Everyday', category: 'Home', thai: "ผ้าห่ม", transliteration: "Pha-hom", german: "Decke", english: "Blanket" },
    { id: 3050, level: 'Everyday', category: 'Home', thai: "แอร์", transliteration: "Air", german: "Klimaanlage", english: "Air Conditioner" },
    { id: 3051, level: 'Everyday', category: 'Home', thai: "พัดลม", transliteration: "Phat-lom", german: "Ventilator", english: "Fan" },
    { id: 3052, level: 'Everyday', category: 'Home', thai: "ไฟ", transliteration: "Fai", german: "Licht/Feuer", english: "Light/Fire" },
    { id: 3053, level: 'Everyday', category: 'Home', thai: "สบู่", transliteration: "Sa-boo", german: "Seife", english: "Soap" },
    { id: 3054, level: 'Everyday', category: 'Home', thai: "ยาสระผม", transliteration: "Ya-sa-phom", german: "Shampoo", english: "Shampoo" },
    { id: 3055, level: 'Everyday', category: 'Home', thai: "แปรงสีฟัน", transliteration: "Praeng-si-fan", german: "Zahnbürste", english: "Toothbrush" },
    { id: 3056, level: 'Everyday', category: 'Home', thai: "ยาสีฟัน", transliteration: "Ya-si-fan", german: "Zahnpasta", english: "Toothpaste" },

    // City & Infrastructure
    { id: 3057, level: 'Everyday', category: 'Places', thai: "ห้าง", transliteration: "Hang", german: "Einkaufszentrum", english: "Mall" },
    { id: 3058, level: 'Everyday', category: 'Places', thai: "ตลาดนัด", transliteration: "Ta-lat Nat", german: "Wochenmarkt", english: "Flea Market" },
    { id: 3059, level: 'Everyday', category: 'Places', thai: "ร้านสะดวกซื้อ", transliteration: "Ran Sa-duak Sue", german: "Convenience Store (7-11)", english: "Convenience Store" },
    { id: 3060, level: 'Everyday', category: 'Places', thai: "ป้ายรถเมล์", transliteration: "Pai Rot-may", german: "Bushaltestelle", english: "Bus Stop" },
    { id: 3061, level: 'Everyday', category: 'Places', thai: "สถานีรถไฟฟ้า", transliteration: "Sa-tha-nee Rot-fai-fah", german: "Skytrain Station", english: "Skytrain Station" },
    { id: 3062, level: 'Everyday', category: 'Places', thai: "ทางด่วน", transliteration: "Thang Duan", german: "Autobahn", english: "Expressway" },
    { id: 3063, level: 'Everyday', category: 'Places', thai: "สะพาน", transliteration: "Sa-phan", german: "Brücke", english: "Bridge" },
    { id: 3064, level: 'Everyday', category: 'Places', thai: "แม่น้ำ", transliteration: "Mae-nam", german: "Fluss", english: "River" },
    { id: 3065, level: 'Everyday', category: 'Places', thai: "สวน", transliteration: "Suan", german: "Park/Garten", english: "Park/Garden" },

    // Abstract & Business
    { id: 3066, level: 'Everyday', category: 'Other', thai: "ความคิด", transliteration: "Khwam-khit", german: "Gedanke/Idee", english: "Idea/Thought" },
    { id: 3067, level: 'Everyday', category: 'Other', thai: "เหตุผล", transliteration: "Het-phon", german: "Grund", english: "Reason" },
    { id: 3068, level: 'Everyday', category: 'Other', thai: "เป้าหมาย", transliteration: "Pao-mai", german: "Ziel", english: "Goal" },
    { id: 3069, level: 'Everyday', category: 'Other', thai: "โอกาส", transliteration: "O-kat", german: "Gelegenheit/Chance", english: "Opportunity" },
    { id: 3070, level: 'Everyday', category: 'Other', thai: "ประสบการณ์", transliteration: "Pra-sop-kan", german: "Erfahrung", english: "Experience" },
    { id: 3071, level: 'Everyday', category: 'Other', thai: "สำคัญ", transliteration: "Sam-khan", german: "Wichtig", english: "Important" },
    { id: 3072, level: 'Everyday', category: 'Other', thai: "พิเศษ", transliteration: "Phi-set", german: "Spezial/Besonders", english: "Special" },
    { id: 3073, level: 'Everyday', category: 'Other', thai: "ธรรมดา", transliteration: "Tham-ma-da", german: "Normal", english: "Normal" },
    { id: 3074, level: 'Everyday', category: 'Other', thai: "จริง", transliteration: "Jing", german: "Echt/Wahr", english: "Real/True" },
    { id: 3075, level: 'Everyday', category: 'Other', thai: "โกหก", transliteration: "Ko-hok", german: "Lügen", english: "Lie" },
    { id: 3076, level: 'Everyday', category: 'Other', thai: "อันตราย", transliteration: "An-ta-rai", german: "Gefährlich", english: "Dangerous" },
    { id: 3077, level: 'Everyday', category: 'Other', thai: "ปลอดภัย", transliteration: "Plot-phai", german: "Sicher", english: "Safe" },
    { id: 3078, level: 'Everyday', category: 'Other', thai: "ระวัง", transliteration: "Ra-wang", german: "Vorsichtig sein", english: "Be careful" },
    { id: 3079, level: 'Everyday', category: 'Other', thai: "พร้อม", transliteration: "Phrom", german: "Bereit", english: "Ready" },
    { id: 3080, level: 'Everyday', category: 'Other', thai: "เสร็จ", transliteration: "Set", german: "Fertig", english: "Finished" },

    // Technology & Media
    { id: 3081, level: 'Everyday', category: 'Objects', thai: "แอพ", transliteration: "App", german: "App", english: "App" },
    { id: 3082, level: 'Everyday', category: 'Objects', thai: "เน็ต", transliteration: "Net", german: "Internet", english: "Internet" },
    { id: 3083, level: 'Everyday', category: 'Objects', thai: "ไวไฟ", transliteration: "Wifi", german: "WLAN", english: "Wifi" },
    { id: 3084, level: 'Everyday', category: 'Objects', thai: "แบตหมด", transliteration: "Bat Mot", german: "Akku leer", english: "Battery Empty" },
    { id: 3085, level: 'Everyday', category: 'Objects', thai: "ที่ชาร์จ", transliteration: "Thi-chat", german: "Ladegerät", english: "Charger" },

    // Time (Frequency/Duration)
    { id: 3086, level: 'Everyday', category: 'Time', thai: "ตลอดเวลา", transliteration: "Ta-lot Way-la", german: "Die ganze Zeit", english: "All the time" },
    { id: 3087, level: 'Everyday', category: 'Time', thai: "ทันที", transliteration: "Than-thee", german: "Sofort", english: "Immediately" },
    { id: 3088, level: 'Everyday', category: 'Time', thai: "สาย", transliteration: "Sai", german: "Spät", english: "Late" },
    { id: 3089, level: 'Everyday', category: 'Time', thai: "เร็วๆ นี้", transliteration: "Reo-reo Nee", german: "Bald", english: "Soon" },
    { id: 3090, level: 'Everyday', category: 'Time', thai: "นาน", transliteration: "Nan", german: "Lange", english: "Long time" },

    // Animals (Common)
    { id: 3091, level: 'Everyday', category: 'Animals', thai: "หมา", transliteration: "Ma", german: "Hund", english: "Dog" },
    { id: 3092, level: 'Everyday', category: 'Animals', thai: "แมว", transliteration: "Maew", german: "Katze", english: "Cat" },
    { id: 3093, level: 'Everyday', category: 'Animals', thai: "นก", transliteration: "Nok", german: "Vogel", english: "Bird" },
    { id: 3094, level: 'Everyday', category: 'Animals', thai: "ช้าง", transliteration: "Chang", german: "Elefant", english: "Elephant" },
    { id: 3095, level: 'Everyday', category: 'Animals', thai: "ลิง", transliteration: "Ling", german: "Affe", english: "Monkey" },
    { id: 3096, level: 'Everyday', category: 'Animals', thai: "ยุง", transliteration: "Yung", german: "Mücke", english: "Mosquito" },
    { id: 3097, level: 'Everyday', category: 'Animals', thai: "มด", transliteration: "Mot", german: "Ameise", english: "Ant" },
    { id: 3098, level: 'Everyday', category: 'Animals', thai: "งู", transliteration: "Ngu", german: "Schlange", english: "Snake" },
    { id: 3099, level: 'Everyday', category: 'Animals', thai: "ควาย", transliteration: "Khwai", german: "Büffel", english: "Buffalo" },
    { id: 3100, level: 'Everyday', category: 'Animals', thai: "เสือ", transliteration: "Suea", german: "Tiger", english: "Tiger" },

    // --- Level Numbers: 1-100 ---
    { id: 4001, level: 'Numbers', category: 'Numbers', thai: "หนึ่ง", transliteration: "Nueng", german: "1", english: "1" },
    { id: 4002, level: 'Numbers', category: 'Numbers', thai: "สอง", transliteration: "Song", german: "2", english: "2" },
    { id: 4003, level: 'Numbers', category: 'Numbers', thai: "สาม", transliteration: "Sam", german: "3", english: "3" },
    { id: 4004, level: 'Numbers', category: 'Numbers', thai: "สี่", transliteration: "Si", german: "4", english: "4" },
    { id: 4005, level: 'Numbers', category: 'Numbers', thai: "ห้า", transliteration: "Ha", german: "5", english: "5" },
    { id: 4006, level: 'Numbers', category: 'Numbers', thai: "หก", transliteration: "Hok", german: "6", english: "6" },
    { id: 4007, level: 'Numbers', category: 'Numbers', thai: "เจ็ด", transliteration: "Jet", german: "7", english: "7" },
    { id: 4008, level: 'Numbers', category: 'Numbers', thai: "แปด", transliteration: "Paet", german: "8", english: "8" },
    { id: 4009, level: 'Numbers', category: 'Numbers', thai: "เก้า", transliteration: "Kao", german: "9", english: "9" },
    { id: 4010, level: 'Numbers', category: 'Numbers', thai: "สิบ", transliteration: "Sip", german: "10", english: "10" },
    { id: 4011, level: 'Numbers', category: 'Numbers', thai: "สิบเอ็ด", transliteration: "Sip-et", german: "11", english: "11" },
    { id: 4012, level: 'Numbers', category: 'Numbers', thai: "สิบสอง", transliteration: "Sip-Song", german: "12", english: "12" },
    { id: 4013, level: 'Numbers', category: 'Numbers', thai: "สิบสาม", transliteration: "Sip-Sam", german: "13", english: "13" },
    { id: 4014, level: 'Numbers', category: 'Numbers', thai: "สิบสี่", transliteration: "Sip-Si", german: "14", english: "14" },
    { id: 4015, level: 'Numbers', category: 'Numbers', thai: "สิบห้า", transliteration: "Sip-Ha", german: "15", english: "15" },
    { id: 4016, level: 'Numbers', category: 'Numbers', thai: "สิบหก", transliteration: "Sip-Hok", german: "16", english: "16" },
    { id: 4017, level: 'Numbers', category: 'Numbers', thai: "สิบเจ็ด", transliteration: "Sip-Jet", german: "17", english: "17" },
    { id: 4018, level: 'Numbers', category: 'Numbers', thai: "สิบแปด", transliteration: "Sip-Paet", german: "18", english: "18" },
    { id: 4019, level: 'Numbers', category: 'Numbers', thai: "สิบเก้า", transliteration: "Sip-Kao", german: "19", english: "19" },
    { id: 4020, level: 'Numbers', category: 'Numbers', thai: "ยี่สิบ", transliteration: "Yee-sip", german: "20", english: "20" },
    { id: 4021, level: 'Numbers', category: 'Numbers', thai: "ยี่สิบเอ็ด", transliteration: "Yee-sip-et", german: "21", english: "21" },
    { id: 4022, level: 'Numbers', category: 'Numbers', thai: "ยี่สิบสอง", transliteration: "Yee-sip-Song", german: "22", english: "22" },
    { id: 4023, level: 'Numbers', category: 'Numbers', thai: "ยี่สิบสาม", transliteration: "Yee-sip-Sam", german: "23", english: "23" },
    { id: 4024, level: 'Numbers', category: 'Numbers', thai: "ยี่สิบสี่", transliteration: "Yee-sip-Si", german: "24", english: "24" },
    { id: 4025, level: 'Numbers', category: 'Numbers', thai: "ยี่สิบห้า", transliteration: "Yee-sip-Ha", german: "25", english: "25" },
    { id: 4026, level: 'Numbers', category: 'Numbers', thai: "ยี่สิบหก", transliteration: "Yee-sip-Hok", german: "26", english: "26" },
    { id: 4027, level: 'Numbers', category: 'Numbers', thai: "ยี่สิบเจ็ด", transliteration: "Yee-sip-Jet", german: "27", english: "27" },
    { id: 4028, level: 'Numbers', category: 'Numbers', thai: "ยี่สิบแปด", transliteration: "Yee-sip-Paet", german: "28", english: "28" },
    { id: 4029, level: 'Numbers', category: 'Numbers', thai: "ยี่สิบเก้า", transliteration: "Yee-sip-Kao", german: "29", english: "29" },
    { id: 4030, level: 'Numbers', category: 'Numbers', thai: "สามสิบ", transliteration: "Sam-sip", german: "30", english: "30" },
    { id: 4031, level: 'Numbers', category: 'Numbers', thai: "สามสิบเอ็ด", transliteration: "Sam-sip-et", german: "31", english: "31" },
    { id: 4032, level: 'Numbers', category: 'Numbers', thai: "สามสิบสอง", transliteration: "Sam-sip-Song", german: "32", english: "32" },
    { id: 4033, level: 'Numbers', category: 'Numbers', thai: "สามสิบสาม", transliteration: "Sam-sip-Sam", german: "33", english: "33" },
    { id: 4034, level: 'Numbers', category: 'Numbers', thai: "สามสิบสี่", transliteration: "Sam-sip-Si", german: "34", english: "34" },
    { id: 4035, level: 'Numbers', category: 'Numbers', thai: "สามสิบห้า", transliteration: "Sam-sip-Ha", german: "35", english: "35" },
    { id: 4036, level: 'Numbers', category: 'Numbers', thai: "สามสิบหก", transliteration: "Sam-sip-Hok", german: "36", english: "36" },
    { id: 4037, level: 'Numbers', category: 'Numbers', thai: "สามสิบเจ็ด", transliteration: "Sam-sip-Jet", german: "37", english: "37" },
    { id: 4038, level: 'Numbers', category: 'Numbers', thai: "สามสิบแปด", transliteration: "Sam-sip-Paet", german: "38", english: "38" },
    { id: 4039, level: 'Numbers', category: 'Numbers', thai: "สามสิบเก้า", transliteration: "Sam-sip-Kao", german: "39", english: "39" },
    { id: 4040, level: 'Numbers', category: 'Numbers', thai: "สี่สิบ", transliteration: "Si-sip", german: "40", english: "40" },
    { id: 4041, level: 'Numbers', category: 'Numbers', thai: "สี่สิบเอ็ด", transliteration: "Si-sip-et", german: "41", english: "41" },
    { id: 4042, level: 'Numbers', category: 'Numbers', thai: "สี่สิบสอง", transliteration: "Si-sip-Song", german: "42", english: "42" },
    { id: 4043, level: 'Numbers', category: 'Numbers', thai: "สี่สิบสาม", transliteration: "Si-sip-Sam", german: "43", english: "43" },
    { id: 4044, level: 'Numbers', category: 'Numbers', thai: "สี่สิบสี่", transliteration: "Si-sip-Si", german: "44", english: "44" },
    { id: 4045, level: 'Numbers', category: 'Numbers', thai: "สี่สิบห้า", transliteration: "Si-sip-Ha", german: "45", english: "45" },
    { id: 4046, level: 'Numbers', category: 'Numbers', thai: "สี่สิบหก", transliteration: "Si-sip-Hok", german: "46", english: "46" },
    { id: 4047, level: 'Numbers', category: 'Numbers', thai: "สี่สิบเจ็ด", transliteration: "Si-sip-Jet", german: "47", english: "47" },
    { id: 4048, level: 'Numbers', category: 'Numbers', thai: "สี่สิบแปด", transliteration: "Si-sip-Paet", german: "48", english: "48" },
    { id: 4049, level: 'Numbers', category: 'Numbers', thai: "สี่สิบเก้า", transliteration: "Si-sip-Kao", german: "49", english: "49" },
    { id: 4050, level: 'Numbers', category: 'Numbers', thai: "ห้าสิบ", transliteration: "Ha-sip", german: "50", english: "50" },
    { id: 4051, level: 'Numbers', category: 'Numbers', thai: "ห้าสิบเอ็ด", transliteration: "Ha-sip-et", german: "51", english: "51" },
    { id: 4052, level: 'Numbers', category: 'Numbers', thai: "ห้าสิบสอง", transliteration: "Ha-sip-Song", german: "52", english: "52" },
    { id: 4053, level: 'Numbers', category: 'Numbers', thai: "ห้าสิบสาม", transliteration: "Ha-sip-Sam", german: "53", english: "53" },
    { id: 4054, level: 'Numbers', category: 'Numbers', thai: "ห้าสิบสี่", transliteration: "Ha-sip-Si", german: "54", english: "54" },
    { id: 4055, level: 'Numbers', category: 'Numbers', thai: "ห้าสิบห้า", transliteration: "Ha-sip-Ha", german: "55", english: "55" },
    { id: 4056, level: 'Numbers', category: 'Numbers', thai: "ห้าสิบหก", transliteration: "Ha-sip-Hok", german: "56", english: "56" },
    { id: 4057, level: 'Numbers', category: 'Numbers', thai: "ห้าสิบเจ็ด", transliteration: "Ha-sip-Jet", german: "57", english: "57" },
    { id: 4058, level: 'Numbers', category: 'Numbers', thai: "ห้าสิบแปด", transliteration: "Ha-sip-Paet", german: "58", english: "58" },
    { id: 4059, level: 'Numbers', category: 'Numbers', thai: "ห้าสิบเก้า", transliteration: "Ha-sip-Kao", german: "59", english: "59" },
    { id: 4060, level: 'Numbers', category: 'Numbers', thai: "หกสิบ", transliteration: "Hok-sip", german: "60", english: "60" },
    { id: 4061, level: 'Numbers', category: 'Numbers', thai: "หกสิบเอ็ด", transliteration: "Hok-sip-et", german: "61", english: "61" },
    { id: 4062, level: 'Numbers', category: 'Numbers', thai: "หกสิบสอง", transliteration: "Hok-sip-Song", german: "62", english: "62" },
    { id: 4063, level: 'Numbers', category: 'Numbers', thai: "หกสิบสาม", transliteration: "Hok-sip-Sam", german: "63", english: "63" },
    { id: 4064, level: 'Numbers', category: 'Numbers', thai: "หกสิบสี่", transliteration: "Hok-sip-Si", german: "64", english: "64" },
    { id: 4065, level: 'Numbers', category: 'Numbers', thai: "หกสิบห้า", transliteration: "Hok-sip-Ha", german: "65", english: "65" },
    { id: 4066, level: 'Numbers', category: 'Numbers', thai: "หกสิบหก", transliteration: "Hok-sip-Hok", german: "66", english: "66" },
    { id: 4067, level: 'Numbers', category: 'Numbers', thai: "หกสิบเจ็ด", transliteration: "Hok-sip-Jet", german: "67", english: "67" },
    { id: 4068, level: 'Numbers', category: 'Numbers', thai: "หกสิบแปด", transliteration: "Hok-sip-Paet", german: "68", english: "68" },
    { id: 4069, level: 'Numbers', category: 'Numbers', thai: "หกสิบเก้า", transliteration: "Hok-sip-Kao", german: "69", english: "69" },
    { id: 4070, level: 'Numbers', category: 'Numbers', thai: "เจ็ดสิบ", transliteration: "Jet-sip", german: "70", english: "70" },
    { id: 4071, level: 'Numbers', category: 'Numbers', thai: "เจ็ดสิบเอ็ด", transliteration: "Jet-sip-et", german: "71", english: "71" },
    { id: 4072, level: 'Numbers', category: 'Numbers', thai: "เจ็ดสิบสอง", transliteration: "Jet-sip-Song", german: "72", english: "72" },
    { id: 4073, level: 'Numbers', category: 'Numbers', thai: "เจ็ดสิบสาม", transliteration: "Jet-sip-Sam", german: "73", english: "73" },
    { id: 4074, level: 'Numbers', category: 'Numbers', thai: "เจ็ดสิบสี่", transliteration: "Jet-sip-Si", german: "74", english: "74" },
    { id: 4075, level: 'Numbers', category: 'Numbers', thai: "เจ็ดสิบห้า", transliteration: "Jet-sip-Ha", german: "75", english: "75" },
    { id: 4076, level: 'Numbers', category: 'Numbers', thai: "เจ็ดสิบหก", transliteration: "Jet-sip-Hok", german: "76", english: "76" },
    { id: 4077, level: 'Numbers', category: 'Numbers', thai: "เจ็ดสิบเจ็ด", transliteration: "Jet-sip-Jet", german: "77", english: "77" },
    { id: 4078, level: 'Numbers', category: 'Numbers', thai: "เจ็ดสิบแปด", transliteration: "Jet-sip-Paet", german: "78", english: "78" },
    { id: 4079, level: 'Numbers', category: 'Numbers', thai: "เจ็ดสิบเก้า", transliteration: "Jet-sip-Kao", german: "79", english: "79" },
    { id: 4080, level: 'Numbers', category: 'Numbers', thai: "แปดสิบ", transliteration: "Paet-sip", german: "80", english: "80" },
    { id: 4081, level: 'Numbers', category: 'Numbers', thai: "แปดสิบเอ็ด", transliteration: "Paet-sip-et", german: "81", english: "81" },
    { id: 4082, level: 'Numbers', category: 'Numbers', thai: "แปดสิบสอง", transliteration: "Paet-sip-Song", german: "82", english: "82" },
    { id: 4083, level: 'Numbers', category: 'Numbers', thai: "แปดสิบสาม", transliteration: "Paet-sip-Sam", german: "83", english: "83" },
    { id: 4084, level: 'Numbers', category: 'Numbers', thai: "แปดสิบสี่", transliteration: "Paet-sip-Si", german: "84", english: "84" },
    { id: 4085, level: 'Numbers', category: 'Numbers', thai: "แปดสิบห้า", transliteration: "Paet-sip-Ha", german: "85", english: "85" },
    { id: 4086, level: 'Numbers', category: 'Numbers', thai: "แปดสิบหก", transliteration: "Paet-sip-Hok", german: "86", english: "86" },
    { id: 4087, level: 'Numbers', category: 'Numbers', thai: "แปดสิบเจ็ด", transliteration: "Paet-sip-Jet", german: "87", english: "87" },
    { id: 4088, level: 'Numbers', category: 'Numbers', thai: "แปดสิบแปด", transliteration: "Paet-sip-Paet", german: "88", english: "88" },
    { id: 4089, level: 'Numbers', category: 'Numbers', thai: "แปดสิบเก้า", transliteration: "Paet-sip-Kao", german: "89", english: "89" },
    { id: 4090, level: 'Numbers', category: 'Numbers', thai: "เก้าสิบ", transliteration: "Kao-sip", german: "90", english: "90" },
    { id: 4091, level: 'Numbers', category: 'Numbers', thai: "เก้าสิบเอ็ด", transliteration: "Kao-sip-et", german: "91", english: "91" },
    { id: 4092, level: 'Numbers', category: 'Numbers', thai: "เก้าสิบสอง", transliteration: "Kao-sip-Song", german: "92", english: "92" },
    { id: 4093, level: 'Numbers', category: 'Numbers', thai: "เก้าสิบสาม", transliteration: "Kao-sip-Sam", german: "93", english: "93" },
    { id: 4094, level: 'Numbers', category: 'Numbers', thai: "เก้าสิบสี่", transliteration: "Kao-sip-Si", german: "94", english: "94" },
    { id: 4095, level: 'Numbers', category: 'Numbers', thai: "เก้าสิบห้า", transliteration: "Kao-sip-Ha", german: "95", english: "95" },
    { id: 4096, level: 'Numbers', category: 'Numbers', thai: "เก้าสิบหก", transliteration: "Kao-sip-Hok", german: "96", english: "96" },
    { id: 4097, level: 'Numbers', category: 'Numbers', thai: "เก้าสิบเจ็ด", transliteration: "Kao-sip-Jet", german: "97", english: "97" },
    { id: 4098, level: 'Numbers', category: 'Numbers', thai: "เก้าสิบแปด", transliteration: "Kao-sip-Paet", german: "98", english: "98" },
    { id: 4099, level: 'Numbers', category: 'Numbers', thai: "เก้าสิบเก้า", transliteration: "Kao-sip-Kao", german: "99", english: "99" },
    { id: 4100, level: 'Numbers', category: 'Numbers', thai: "หนึ่งร้อย", transliteration: "Nueng-roi", german: "100", english: "100" },
];
