const vocabList = [
    // --- Level A1 (Basics) ---
    { id: 101, level: 'A1', category: 'Greeting', thai: "สวัสดี", transliteration: "Sawatdee", german: "Hallo", english: "Hello" },
    { id: 102, level: 'A1', category: 'Greeting', thai: "ลาก่อน", transliteration: "La gon", german: "Tschüss", english: "Goodbye" },
    { id: 103, level: 'A1', category: 'Basics', thai: "ใช่", transliteration: "Chai", german: "Ja", english: "Yes" },
    { id: 104, level: 'A1', category: 'Basics', thai: "ไม่", transliteration: "Mai", german: "Nein", english: "No" },
    { id: 105, level: 'A1', category: 'Basics', thai: "ขอบคุณ", transliteration: "Khop khun", german: "Danke", english: "Thank you" },
    { id: 106, level: 'A1', category: 'Basics', thai: "ขอโทษ", transliteration: "Khor thot", german: "Entschuldigung", english: "Sorry" },
    { id: 107, level: 'A1', category: 'Pronoun', thai: "ผม", transliteration: "Phom", german: "Ich (männlich)", english: "I (male)" },
    { id: 108, level: 'A1', category: 'Pronoun', thai: "ฉัน", transliteration: "Chan", german: "Ich (weiblich)", english: "I (female)" },
    { id: 109, level: 'A1', category: 'Pronoun', thai: "คุณ", transliteration: "Khun", german: "Du / Sie", english: "You" },
    { id: 110, level: 'A1', category: 'Question', thai: "อะไร", transliteration: "Arai", german: "Was", english: "What" },
    { id: 111, level: 'A1', category: 'Question', thai: "ที่ไหน", transliteration: "Theenai", german: "Wo", english: "Where" },
    { id: 112, level: 'A1', category: 'Question', thai: "เมื่อไหร่", transliteration: "Muearai", german: "Wann", english: "When" },
    { id: 113, level: 'A1', category: 'Question', thai: "ทำไม", transliteration: "Thammai", german: "Warum", english: "Why" },
    { id: 114, level: 'A1', category: 'Question', thai: "อย่างไร", transliteration: "Yangrai", german: "Wie", english: "How" },
    { id: 115, level: 'A1', category: 'Numbers', thai: "หนึ่ง", transliteration: "Nueng", german: "Eins", english: "One" },
    { id: 116, level: 'A1', category: 'Numbers', thai: "สอง", transliteration: "Song", german: "Zwei", english: "Two" },
    { id: 117, level: 'A1', category: 'Numbers', thai: "สาม", transliteration: "Sam", german: "Drei", english: "Three" },
    { id: 118, level: 'A1', category: 'Numbers', thai: "สี่", transliteration: "Si", german: "Vier", english: "Four" },
    { id: 119, level: 'A1', category: 'Numbers', thai: "ห้า", transliteration: "Ha", german: "Fünf", english: "Five" },
    { id: 120, level: 'A1', category: 'Family', thai: "พ่อ", transliteration: "Phor", german: "Vater", english: "Father" },
    { id: 121, level: 'A1', category: 'Family', thai: "แม่", transliteration: "Mae", german: "Mutter", english: "Mother" },
    { id: 122, level: 'A1', category: 'Verbs', thai: "กิน", transliteration: "Kin", german: "Essen", english: "Eat" },
    { id: 123, level: 'A1', category: 'Verbs', thai: "ดื่ม", transliteration: "Deum", german: "Trinken", english: "Drink" },
    { id: 124, level: 'A1', category: 'Verbs', thai: "ไป", transliteration: "Pai", german: "Gehen", english: "Go" },
    { id: 125, level: 'A1', category: 'Verbs', thai: "มา", transliteration: "Ma", german: "Kommen", english: "Come" },

    // --- Level A2 (Elementary) ---
    { id: 201, level: 'A2', category: 'Time', thai: "วันนี้", transliteration: "Wan-nee", german: "Heute", english: "Today" },
    { id: 202, level: 'A2', category: 'Time', thai: "พรุ่งนี้", transliteration: "Prung-nee", german: "Morgen", english: "Tomorrow" },
    { id: 203, level: 'A2', category: 'Time', thai: "เมื่อวาน", transliteration: "Meua-wan", german: "Gestern", english: "Yesterday" },
    { id: 204, level: 'A2', category: 'Food', thai: "ข้าวผัด", transliteration: "Khao Pad", german: "Gebratener Reis", english: "Fried Rice" },
    { id: 205, level: 'A2', category: 'Food', thai: "เผ็ด", transliteration: "Phet", german: "Scharf", english: "Spicy" },
    { id: 206, level: 'A2', category: 'Places', thai: "โรงพยาบาล", transliteration: "Rong-phaya-ban", german: "Krankenhaus", english: "Hospital" },
    { id: 207, level: 'A2', category: 'Places', thai: "สนามบิน", transliteration: "Sanam-bin", german: "Flughafen", english: "Airport" },
    { id: 208, level: 'A2', category: 'Travel', thai: "ตั๋ว", transliteration: "Tua", german: "Ticket", english: "Ticket" },
    { id: 209, level: 'A2', category: 'Health', thai: "ป่วย", transliteration: "Puay", german: "Krank", english: "Sick" },
    { id: 210, level: 'A2', category: 'Verbs', thai: "ชอบ", transliteration: "Chop", german: "Mögen", english: "Like" },
    { id: 211, level: 'A2', category: 'Verbs', thai: "อยาก", transliteration: "Yak", german: "Wollen", english: "Want" },
    { id: 212, level: 'A2', category: 'Shopping', thai: "ราคา", transliteration: "Ra-kha", german: "Preis", english: "Price" },
    { id: 213, level: 'A2', category: 'Shopping', thai: "แพง", transliteration: "Phaeng", german: "Teuer", english: "Expensive" },
    { id: 214, level: 'A2', category: 'Shopping', thai: "ถูก", transliteration: "Thook", german: "Billig", english: "Cheap" },
    { id: 215, level: 'A2', category: 'Colors', thai: "สีแดง", transliteration: "Si Daeng", german: "Rot", english: "Red" },
    { id: 216, level: 'A2', category: 'Colors', thai: "สีน้ำเงิน", transliteration: "Si Nam-ngoen", german: "Blau", english: "Blue" },
    { id: 217, level: 'A2', category: 'Colors', thai: "สีขาว", transliteration: "Si Khao", german: "Weiß", english: "White" },
    { id: 218, level: 'A2', category: 'Colors', thai: "สีดำ", transliteration: "Si Dam", german: "Schwarz", english: "Black" },
    { id: 219, level: 'A2', category: 'Weather', thai: "ร้อน", transliteration: "Ron", german: "Heiß", english: "Hot" },
    { id: 220, level: 'A2', category: 'Weather', thai: "หนาว", transliteration: "Nao", german: "Kalt", english: "Cold" },

    // --- Daily Life (Alltag) ---
    { id: 301, level: 'Everyday', category: 'Objects', thai: "โทรศัพท์", transliteration: "Thor-a-sap", german: "Telefon", english: "Telephone" },
    { id: 302, level: 'Everyday', category: 'Objects', thai: "กุญแจ", transliteration: "Kun-jae", german: "Schlüssel", english: "Key" },
    { id: 303, level: 'Everyday', category: 'Objects', thai: "เงิน", transliteration: "Ngoen", german: "Geld", english: "Money" },
    { id: 304, level: 'Everyday', category: 'Activities', thai: "ทำงาน", transliteration: "Tham-ngan", german: "Arbeiten", english: "Work" },
    { id: 305, level: 'Everyday', category: 'Activities', thai: "เรียน", transliteration: "Rian", german: "Lernen", english: "Study/Learn" },
    { id: 306, level: 'Everyday', category: 'Activities', thai: "นอน", transliteration: "Non", german: "Schlafen", english: "Sleep" },
    { id: 307, level: 'Everyday', category: 'Transport', thai: "รถ", transliteration: "Rot", german: "Auto", english: "Car" },
    { id: 308, level: 'Everyday', category: 'Transport', thai: "รถเมล์", transliteration: "Rot-may", german: "Bus", english: "Bus" },
    { id: 309, level: 'Everyday', category: 'Transport', thai: "รถไฟ", transliteration: "Rot-fai", german: "Zug", english: "Train" },
    { id: 310, level: 'Everyday', category: 'Home', thai: "บ้าน", transliteration: "Baan", german: "Haus", english: "House" },
    { id: 311, level: 'Everyday', category: 'Home', thai: "ห้อง", transliteration: "Hong", german: "Zimmer", english: "Room" },
    { id: 312, level: 'Everyday', category: 'Social', thai: "เพื่อน", transliteration: "Peuan", german: "Freund", english: "Friend" },
    { id: 313, level: 'Everyday', category: 'Social', thai: "แฟน", transliteration: "Fan", german: "Freund/in (Partner)", english: "Boyfriend/Girlfriend" },
    { id: 314, level: 'Everyday', category: 'Feelings', thai: "มีความสุข", transliteration: "Mee kwahm sook", german: "Glücklich", english: "Happy" },
    { id: 315, level: 'Everyday', category: 'Feelings', thai: "เหนื่อย", transliteration: "Nuay", german: "Müde", english: "Tired" },
    { id: 316, level: 'Everyday', category: 'Feelings', thai: "หิว", transliteration: "Hiw", german: "Hungrig", english: "Hungry" },
    { id: 317, level: 'Everyday', category: 'Body', thai: "มือ", transliteration: "Meu", german: "Hand", english: "Hand" },
    { id: 318, level: 'Everyday', category: 'Body', thai: "หัว", transliteration: "Hua", german: "Kopf", english: "Head" },
    { id: 319, level: 'Everyday', category: 'Body', thai: "ตา", transliteration: "Taa", german: "Auge", english: "Eye" },
    { id: 320, level: 'Everyday', category: 'Body', thai: "ปาก", transliteration: "Paak", german: "Mund", english: "Mouth" }

    // Note: Due to size constraints, this list contains ~60 representative items. 
    // To reach 200 per category, you would simply continue this pattern with IDs incrementing.
];
