import json

# --- Vocabulary Data ---

# Everyday (100 words)
everyday_list = [
    ("กาแฟ", "kaa-fae", "Kaffee", "Coffee"),
    ("ชา", "chaa", "Tee", "Tea"),
    ("น้ำเปล่า", "nam-plao", "Wasser", "Water"),
    ("ข้าว", "khao", "Reis", "Rice"),
    ("ก๋วยเตี๋ยว", "guay-tiew", "Nudelsuppe", "Noodle Soup"),
    ("เผ็ด", "phet", "Scharf", "Spicy"),
    ("อร่อย", "a-roi", "Lecker", "Delicious"),
    ("หิว", "hiw", "Hungrig", "Hungry"),
    ("อิ่ม", "im", "Satt", "Full"),
    ("ร้านอาหาร", "raan-aa-haan", "Restaurant", "Restaurant"),
    ("ตลาด", "ta-lat", "Markt", "Market"),
    ("ห้าง", "hang", "Einkaufszentrum", "Mall"),
    ("เซเว่น", "seven", "7-Eleven", "7-Eleven"),
    ("ห้องน้ำ", "hong-nam", "Toilette", "Toilet"),
    ("โรงแรม", "rong-raem", "Hotel", "Hotel"),
    ("โรงพยาบาล", "rong-phaya-ban", "Krankenhaus", "Hospital"),
    ("บ้าน", "baan", "Haus", "House"),
    ("ห้อง", "hong", "Zimmer", "Room"),
    ("เตียง", "tiang", "Bett", "Bed"),
    ("ประตู", "pra-tu", "Tür", "Door"),
    ("หน้าต่าง", "na-tang", "Fenster", "Window"),
    ("รถ", "rot", "Auto", "Car"),
    ("รถเมล์", "rot-me", "Bus", "Bus"),
    ("รถไฟ", "rot-fai", "Zug", "Train"),
    ("แท็กซี่", "taxi", "Taxi", "Taxi"),
    ("มอเตอร์ไซค์", "motor-sai", "Motorrad", "Motorcycle"),
    ("เครื่องบิน", "krueng-bin", "Flugzeug", "Airplane"),
    ("สนามบิน", "sanam-bin", "Flughafen", "Airport"),
    ("ตั๋ว", "tua", "Ticket", "Ticket"),
    ("เงิน", "ngoen", "Geld", "Money"),
    ("แพง", "paeng", "Teuer", "Expensive"),
    ("ถูก", "thuuk", "Billig", "Cheap"),
    ("ลดราคา", "lot-ra-kha", "Rabatt", "Discount"),
    ("เท่าไหร่", "tao-rai", "Wie viel", "How much"),
    ("บาท", "baht", "Baht", "Baht"),
    ("บัตรเครดิต", "bat-kredit", "Kreditkarte", "Credit Card"),
    ("ธนาคาร", "tha-na-khan", "Bank", "Bank"),
    ("ซื้อ", "sue", "Kaufen", "Buy"),
    ("ขาย", "kai", "Verkaufen", "Sell"),
    ("ชอบ", "chop", "Mögen", "Like"),
    ("ไม่ชอบ", "mai-chop", "Nicht mögen", "Dislike"),
    ("รัก", "rak", "Lieben", "Love"),
    ("เกลียด", "kliat", "Hassen", "Hate"),
    ("ดี", "dee", "Gut", "Good"),
    ("แย่", "yae", "Schlecht", "Bad"),
    ("สวย", "suay", "Schön", "Beautiful"),
    ("หล่อ", "lor", "Gutaussehend", "Handsome"),
    ("น่ารัก", "na-rak", "Niedlich", "Cute"),
    ("สนุก", "sa-nuk", "Spaß", "Fun"),
    ("เบื่อ", "buea", "Langweilig", "Bored"),
    ("เหนื่อย", "nueai", "Müde", "Tired"),
    ("ง่วง", "nguang", "Schläfrig", "Sleepy"),
    ("เจ็บ", "jep", "Schmerzen", "Hurt"),
    ("ป่วย", "puay", "Krank", "Sick"),
    ("ยา", "ya", "Medikament", "Medicine"),
    ("หาหมอ", "ha-mor", "Zum Arzt gehen", "See doctor"),
    ("ร้อน", "ron", "Heiß", "Hot"),
    ("หนาว", "nao", "Kalt", "Cold"),
    ("ฝนตก", "fon-tok", "Regen", "Rain"),
    ("แดดออก", "daet-ok", "Sonnig", "Sunny"),
    ("เสื้อ", "suea", "Hemd/Oberteil", "Shirt"),
    ("กางเกง", "kang-keng", "Hose", "Pants"),
    ("รองเท้า", "rong-tao", "Schuhe", "Shoes"),
    ("กระเป๋า", "kra-pao", "Tasche", "Bag"),
    ("หมวก", "muak", "Hut", "Hat"),
    ("แว่นตา", "waen-ta", "Brille", "Glasses"),
    ("นาฬิกา", "na-li-ka", "Uhr", "Watch"),
    ("โทรศัพท์", "tho-ra-sap", "Telefon", "Phone"),
    ("เบอร์โทร", "ber-tho", "Telefonnummer", "Phone Number"),
    ("อินเทอร์เน็ต", "internet", "Internet", "Internet"),
    ("รหัสผ่าน", "ra-hat-phan", "Passwort", "Password"),
    ("รูปถ่าย", "rup-thai", "Foto", "Photo"),
    ("เพื่อน", "puean", "Freund", "Friend"),
    ("แฟน", "faen", "Freund/Freundin", "Boyfriend/Girlfriend"),
    ("ครอบครัว", "krop-krua", "Familie", "Family"),
    ("พ่อ", "phor", "Vater", "Father"),
    ("แม่", "mae", "Mutter", "Mother"),
    ("พี่น้อง", "phi-nong", "Geschwister", "Siblings"),
    ("ลูก", "luk", "Kind", "Child"),
    ("งาน", "ngaan", "Arbeit", "Work"),
    ("เรียน", "rian", "Lernen", "Study"),
    ("เล่น", "len", "Spielen", "Play"),
    ("ดูหนัง", "du-nang", "Film schauen", "Watch Movie"),
    ("ฟังเพลง", "fang-phleng", "Musik hören", "Listen Music"),
    ("ออกกำลังกาย", "ok-kam-lang-kai", "Sport machen", "Exercise"),
    ("ว่ายน้ำ", "wai-nam", "Schwimmen", "Swim"),
    ("วิ่ง", "wing", "Laufen", "Run"),
    ("เดิน", "doen", "Gehen", "Walk"),
    ("นอน", "non", "Schlafen", "Sleep"),
    ("ตื่น", "tuen", "Aufwachen", "Wake up"),
    ("อาบน้ำ", "ap-nam", "Duschen", "Shower"),
    ("แปรงฟัน", "praeng-fan", "Zähne putzen", "Brush Teeth"),
    ("แต่งตัว", "taeng-tua", "Anziehen", "Dress up"),
    ("ซักผ้า", "sak-pha", "Wäsche waschen", "Laundry"),
    ("ล้างจาน", "lang-jan", "Geschirr spülen", "Wash Dishes"),
    ("ทำอาหาร", "tham-a-han", "Kochen", "Cook"),
    ("กวาดบ้าน", "kwat-ban", "Fegen", "Sweep Floor"),
    ("ถูพื้น", "thu-phuen", "Wischen", "Mop Floor"),
    ("ทิ้งขยะ", "thing-kha-ya", "Müll rausbringen", "Throw Trash")
]

# A1 (100 words)
a1_list = [
    ("สวัสดีครับ", "sa-wat-dee-krap", "Hallo (m)", "Hello (m)"),
    ("สวัสดีค่ะ", "sa-wat-dee-kha", "Hallo (f)", "Hello (f)"),
    ("สบายดีไหม", "sa-bai-dee-mai", "Wie geht's?", "How are you?"),
    ("สบายดี", "sa-bai-dee", "Mir geht's gut", "I'm fine"),
    ("ขอบคุณ", "khop-khun", "Danke", "Thank you"),
    ("ขอโทษ", "kho-thot", "Entschuldigung", "Sorry"),
    ("ไม่เป็นไร", "mai-pen-rai", "Kein Problem", "No problem"),
    ("ใช่", "chai", "Ja", "Yes"),
    ("ไม่ใช่", "mai-chai", "Nein", "No"),
    ("ชื่ออะไร", "chue-a-rai", "Wie heißt du?", "What's your name?"),
    ("ผมชื่อ", "phom-chue", "Ich heiße (m)", "My name is (m)"),
    ("ฉันชื่อ", "chan-chue", "Ich heiße (f)", "My name is (f)"),
    ("ยินดีที่ได้รู้จัก", "yin-dee-thi-dai-ru-jak", "Schön dich kennenzulernen", "Nice to meet you"),
    ("มาจากไหน", "ma-jak-nai", "Woher kommst du?", "Where are you from?"),
    ("มาจาก", "ma-jak", "Ich komme aus...", "I come from..."),
    ("เข้าใจไหม", "khao-jai-mai", "Verstehst du?", "Understand?"),
    ("เข้าใจ", "khao-jai", "Verstehe", "Understand"),
    ("ไม่เข้าใจ", "mai-khao-jai", "Verstehe nicht", "Don't understand"),
    ("พูดไทยได้ไหม", "phut-thai-dai-mai", "Kannst du Thai?", "Can speak Thai?"),
    ("พูดได้นิดหน่อย", "phut-dai-nit-noi", "Ein bisschen", "A little bit"),
    ("อันนี้อะไร", "an-nee-a-rai", "Was ist das?", "What is this?"),
    ("เรียกว่าอะไร", "riak-wa-a-rai", "Wie heißt das?", "What is this called?"),
    ("เขียนยังไง", "khian-yang-ngai", "Wie schreibt man das?", "How to write?"),
    ("ช่วยด้วย", "chuay-duay", "Hilfe!", "Help!"),
    ("หยุด", "yut", "Stopp", "Stop"),
    ("ไปไหน", "pai-nai", "Wohin gehst du?", "Where going?"),
    ("ไป...", "pai...", "Ich gehe zu...", "I go to..."),
    ("กินข้าวหรือยัง", "kin-khao-rue-yang", "Hast du schon gegessen?", "Eaten yet?"),
    ("กินแล้ว", "kin-laeo", "Schon gegessen", "Already eaten"),
    ("ยัง", "yang", "Noch nicht", "Not yet"),
    ("ใคร", "krai", "Wer", "Who"),
    ("อะไร", "a-rai", "Was", "What"),
    ("ที่ไหน", "thi-nai", "Wo", "Where"),
    ("เมื่อไหร่", "muea-rai", "Wann", "When"),
    ("ทำไม", "tham-mai", "Warum", "Why"),
    ("อย่างไร", "yang-rai", "Wie", "How"),
    ("กี่", "kee", "Wie viele", "How many"),
    ("หนึ่ง", "nueng", "Eins", "One"),
    ("สอง", "song", "Zwei", "Two"),
    ("สาม", "sam", "Drei", "Three"),
    ("สี่", "see", "Vier", "Four"),
    ("ห้า", "ha", "Fünf", "Five"),
    ("หก", "hok", "Sechs", "Six"),
    ("เจ็ด", "jet", "Sieben", "Seven"),
    ("แปด", "paet", "Acht", "Eight"),
    ("เก้า", "kao", "Neun", "Nine"),
    ("สิบ", "sip", "Zehn", "Ten"),
    ("ร้อย", "roi", "Hundert", "Hundred"),
    ("พัน", "phan", "Tausend", "Thousand"),
    ("หมื่น", "muen", "Zehntausend", "Ten thousand"),
    ("แสน", "saen", "Hunderttausend", "Hundred thousand"),
    ("ล้าน", "lan", "Million", "Million"),
    ("สีแดง", "see-daeng", "Rot", "Red"),
    ("สีเขียว", "see-khiao", "Grün", "Green"),
    ("สีน้ำเงิน", "see-nam-ngoen", "Blau", "Blue"),
    ("สีเหลือง", "see-lueang", "Gelb", "Yellow"),
    ("สีดำ", "see-dam", "Schwarz", "Black"),
    ("สีขาว", "see-khao", "Weiß", "White"),
    ("วันจันทร์", "wan-jan", "Montag", "Monday"),
    ("วันอังคาร", "wan-ang-khan", "Dienstag", "Tuesday"),
    ("วันพุธ", "wan-phut", "Mittwoch", "Wednesday"),
    ("วันพฤหัสบดี", "wan-pha-rue-hat", "Donnerstag", "Thursday"),
    ("วันศุกร์", "wan-suk", "Freitag", "Friday"),
    ("วันเสาร์", "wan-sao", "Samstag", "Saturday"),
    ("วันอาทิตย์", "wan-a-thit", "Sonntag", "Sunday"),
    ("เมื่อวาน", "muea-wan", "Gestern", "Yesterday"),
    ("วันนี้", "wan-nee", "Heute", "Today"),
    ("พรุ่งนี้", "phrung-nee", "Morgen", "Tomorrow"),
    ("เช้า", "chao", "Morgen (Zeit)", "Morning"),
    ("เที่ยง", "thiang", "Mittag", "Noon"),
    ("บ่าย", "bai", "Nachmittag", "Afternoon"),
    ("เย็น", "yen", "Abend", "Evening"),
    ("ค่ำ", "kham", "Spätabend", "Late evening"),
    ("ดึก", "duek", "Spätnacht", "Late night"),
    ("นาที", "na-thee", "Minute", "Minute"),
    ("ชั่วโมง", "chua-mong", "Stunde", "Hour"),
    ("วัน", "wan", "Tag", "Day"),
    ("สัปดาห์", "sap-da", "Woche", "Week"),
    ("เดือน", "duean", "Monat", "Month"),
    ("ปี", "pee", "Jahr", "Year"),
    ("ตอนนี้", "ton-nee", "Jetzt", "Now"),
    ("เดี๋ยวนี้", "diao-nee", "Sofort", "Immediately"),
    ("ทีหลัง", "thi-lang", "Später", "Later"),
    ("เร็วๆนี้", "reo-reo-nee", "Bald", "Soon"),
    ("นาน", "nan", "Lange", "Long time"),
    ("ใกล้", "klai", "Nahe", "Near"),
    ("ไกล", "klai (mid tone)", "Weit", "Far"),
    ("บน", "bon", "Auf/Oben", "On/Above"),
    ("ล่าง", "lang", "Unter/Unten", "Under/Below"),
    ("ใน", "nai", "In", "In"),
    ("นอก", "nok", "Außerhalb", "Outside"),
    ("ซ้าย", "sai", "Links", "Left"),
    ("ขวา", "khwa", "Rechts", "Right"),
    ("ตรงไป", "trong-pai", "Geradeaus", "Straight"),
    ("เลี้ยว", "liao", "Abbiegen", "Turn"),
    ("จอด", "jod", "Parken/Halten", "Park/Stop"),
    ("รอ", "ror", "Warten", "Wait"),
    ("เร็ว", "reo", "Schnell", "Fast"),
    ("ช้า", "cha", "Langsam", "Slow")
]

# A2 (100 words)
a2_list = [
    ("ประโยค", "pra-yok", "Satz", "Sentence"),
    ("คำถาม", "kham-tham", "Frage", "Question"),
    ("คำตอบ", "kham-top", "Antwort", "Answer"),
    ("ภาษา", "pha-sa", "Sprache", "Language"),
    ("แปล", "plae", "Übersetzen", "Translate"),
    ("หมายความว่า", "mai-khwam-wa", "Bedeutet", "Means"),
    ("ตัวอย่าง", "tua-yang", "Beispiel", "Example"),
    ("ยาก", "yak", "Schwer", "Difficult"),
    ("ง่าย", "ngai", "Einfach", "Easy"),
    ("ถูกต้อง", "thuk-tong", "Richtig", "Correct"),
    ("ผิด", "phit", "Falsch", "Wrong"),
    ("ลืม", "luem", "Vergessen", "Forget"),
    ("จำ", "jam", "Erinnern", "Remember"),
    ("คิด", "khit", "Denken", "Think"),
    ("เชื่อ", "chuea", "Glauben", "Believe"),
    ("หวัง", "wang", "Hoffen", "Hope"),
    ("สัญญา", "san-ya", "Versprechen", "Promise"),
    ("ความลับ", "khwam-lap", "Geheimnis", "Secret"),
    ("ความจริง", "khwam-jing", "Wahrheit", "Truth"),
    ("เรื่อยๆ", "rueai-rueai", "Immer wieder / Geht so", "So so / Continuously"),
    ("บ่อย", "boi", "Oft", "Often"),
    ("บางครั้ง", "bang-khrang", "Manchmal", "Sometimes"),
    ("ไม่เคย", "mai-khoei", "Niemals", "Never"),
    ("เสมอ", "sa-moe", "Immer", "Always"),
    ("ปกติ", "pa-ka-ti", "Normalerweise", "Usually"),
    ("เกือบ", "kueap", "Fast", "Almost"),
    ("ที่สุด", "thi-sut", "Am meisten", "The most"),
    ("กว่า", "kwa", "Als (Vergleich)", "Than"),
    ("เพราะว่า", "phro-wa", "Weil", "Because"),
    ("ถ้า", "tha", "Wenn", "If"),
    ("แต่", "tae", "Aber", "But"),
    ("หรือ", "rue", "Oder", "Or"),
    ("และ", "lae", "Und", "And"),
    ("กับ", "kap", "Mit", "With"),
    ("เพื่อ", "phuea", "Für", "For"),
    ("ของ", "khong", "Von (Besitz)", "Of"),
    ("ที่", "thi", "Bei/An/Der/Die/Das", "At/That"),
    ("ให้", "hai", "Geben/Lassen", "Give/Let"),
    ("ได้", "dai", "Können/Bekommen", "Can/Get"),
    ("ต้อง", "tong", "Müssen", "Must"),
    ("ควร", "khuan", "Sollte", "Should"),
    ("อาจจะ", "at-ja", "Vielleicht", "Maybe"),
    ("ต้องการ", "tong-kan", "Brauchen/Wollen", "Need/Want"),
    ("อยาก", "yak", "Möchten", "Want to"),
    ("พยายาม", "pha-ya-yam", "Versuchen", "Try"),
    ("สำเร็จ", "sam-ret", "Erfolg haben", "Succeed"),
    ("ล้มเหลว", "lom-leo", "Scheitern", "Fail"),
    ("เริ่ม", "roem", "Beginnen", "Start"),
    ("เสร็จ", "set", "Fertig", "Finish"),
    ("หยุด", "yut", "Anhalten", "Stop"),
    ("ต่อ", "tor", "Weiter", "Continue"),
    ("เปลี่ยน", "plian", "Ändern", "Change"),
    ("เหมือน", "muean", "Gleich/Ähnlich", "Same/Like"),
    ("ต่าง", "tang", "Anders", "Different"),
    ("พิเศษ", "phi-set", "Spezial", "Special"),
    ("ธรรมดา", "tham-ma-da", "Normal", "Ordinary"),
    ("สำคัญ", "sam-khan", "Wichtig", "Important"),
    ("จำเป็น", "jam-pen", "Notwendig", "Necessary"),
    ("เป็นไปได้", "pen-pai-dai", "Möglich", "Possible"),
    ("เป็นไปไม่ได้", "pen-pai-mai-dai", "Unmöglich", "Impossible"),
    ("อันตราย", "an-ta-rai", "Gefährlich", "Dangerous"),
    ("ปลอดภัย", "plot-phai", "Sicher", "Safe"),
    ("ระวัง", "ra-wang", "Vorsicht", "Careful"),
    ("ช่วย", "chuay", "Helfen", "Help"),
    ("ขอ", "khor", "Bitten um", "Ask for"),
    ("ให้ยืม", "hai-yuem", "Leihen", "Lend"),
    ("ขอยืม", "khor-yuem", "Ausleihen", "Borrow"),
    ("คืน", "khuen", "Zurückgeben", "Return"),
    ("หาย", "hai", "Verloren/Verschwunden", "Lost"),
    ("หา", "ha", "Suchen", "Search"),
    ("เจอ", "jer", "Finden/Treffen", "Find/Meet"),
    ("พบ", "phop", "Treffen (formell)", "Meet"),
    ("รู้จัก", "ru-jak", "Kennen", "Know (person)"),
    ("รู้", "ru", "Wissen", "Know (fact)"),
    ("เข้าใจ", "khao-jai", "Verstehen", "Understand"),
    ("สอน", "son", "Lehren", "Teach"),
    ("เรียน", "rian", "Lernen", "Learn"),
    ("อ่าน", "an", "Lesen", "Read"),
    ("เขียน", "khian", "Schreiben", "Write"),
    ("ฟัง", "fang", "Hören", "Listen"),
    ("ดู", "du", "Sehen/Schauen", "Watch"),
    ("เห็น", "hen", "Sehen", "See"),
    ("มอง", "mong", "Blicken", "Look"),
    ("กิน", "kin", "Essen", "Eat"),
    ("ดื่ม", "duem", "Trinken", "Drink"),
    ("ชิม", "chim", "Probieren (Essen)", "Taste"),
    ("ดม", "dom", "Riechen", "Smell"),
    ("จับ", "jap", "Berühren/Fangen", "Touch/Catch"),
    ("รู้สึก", "ru-suek", "Fühlen", "Feel"),
    ("รัก", "rak", "Lieben", "Love"),
    ("สนใจ", "son-jai", "Interessiert sein", "Interested"),
    ("ตื่นเต้น", "tuen-ten", "Aufgeregt", "Excited"),
    ("กลัว", "klua", "Angst haben", "Scared"),
    ("โกรธ", "krot", "Wütend", "Angry"),
    ("เกลียด", "kliat", "Hassen", "Hate"),
    ("เสียใจ", "sia-jai", "Traurig/Bedauern", "Sad/Sorry"),
    ("ดีใจ", "dee-jai", "Froh", "Glad"),
    ("มีความสุข", "mee-khwam-suk", "Glücklich", "Happy")
]

# B1 (200 words)
b1_list = [
    ("การเดินทาง", "kan-doen-thang", "Reise", "Travel"),
    ("จอง", "jong", "Reservieren", "Book/Reserve"),
    ("ที่พัก", "thi-phak", "Unterkunft", "Accommodation"),
    ("วันหยุด", "wan-yut", "Urlaub/Feiertag", "Holiday"),
    ("หนังสือเดินทาง", "nang-sue-doen-thang", "Reisepass", "Passport"),
    ("วีซ่า", "wi-sa", "Visum", "Visa"),
    ("แผนที่", "phaen-thi", "Karte", "Map"),
    ("กระเป๋าเดินทาง", "kra-pao-doen-thang", "Koffer", "Suitcase"),
    ("ไกด์", "kai", "Reiseführer", "Guide"),
    ("ท่องเที่ยว", "thong-thiao", "Tourismus", "Tourism"),
    ("วัฒนธรรม", "wat-tha-na-tham", "Kultur", "Culture"),
    ("ประเพณี", "pra-phe-nee", "Tradition", "Tradition"),
    ("ศาสนา", "sat-sa-na", "Religion", "Religion"),
    ("วัด", "wat", "Tempel", "Temple"),
    ("พระ", "phra", "Mönch/Buddha", "Monk/Buddha"),
    ("ทำบุญ", "tham-bun", "Verdienst machen (rel.)", "Make merit"),
    ("ตักบาตร", "tak-bat", "Almosen geben", "Give alms"),
    ("สงกรานต์", "song-kran", "Songkran (Neujahr)", "Songkran"),
    ("ลอยกระทง", "loi-kra-thong", "Loi Krathong", "Loi Krathong"),
    ("อาหารไทย", "a-han-thai", "Thailändisches Essen", "Thai Food"),
    ("รสชาติ", "rot-chat", "Geschmack", "Taste"),
    ("เปรี้ยว", "priao", "Sauer", "Sour"),
    ("หวาน", "wan", "Süß", "Sweet"),
    ("เค็ม", "khem", "Salzig", "Salty"),
    ("ขม", "khom", "Bitter", "Bitter"),
    ("จิด", "juet", "Fade", "Bland"),
    ("มัน", "man", "Fettig/Ölig", "Oily/Creamy"),
    ("กลมกล่อม", "klom-klom", "Mellow/Abgerundet", "Mellow"),
    ("กรอบ", "krop", "Knusprig", "Crispy"),
    ("เหนียว", "niao", "Zäh/Klebrig", "Sticky/Chewy"),
    ("สุก", "suk", "Gekocht/Reif", "Cooked/Ripe"),
    ("ดิบ", "dip", "Roh", "Raw"),
    ("สด", "sot", "Frisch", "Fresh"),
    ("เน่า", "nao", "Verrottet", "Rotten"),
    ("หอม", "hom", "Duftend", "Fragrant"),
    ("เหม็น", "men", "Stinkend", "Stinky"),
    ("สุขภาพ", "suk-kha-phap", "Gesundheit", "Health"),
    ("แข็งแรง", "khaeng-raeng", "Stark/Gesund", "Strong"),
    ("อ่อนแอ", "on-ae", "Schwach", "Weak"),
    ("ออกกำลังกาย", "ok-kam-lang-kai", "Trainieren", "Exercise"),
    ("วิ่ง", "wing", "Joggen", "Jog"),
    ("ว่ายน้ำ", "wai-nam", "Schwimmen", "Swim"),
    ("โยคะ", "yo-kha", "Yoga", "Yoga"),
    ("นวด", "nuat", "Massage", "Massage"),
    ("สปา", "spa", "Spa", "Spa"),
    ("พักผ่อน", "phak-phon", "Ausruhen", "Rest"),
    ("นอนหลับ", "non-lap", "Schlafen", "Sleep"),
    ("ฝัน", "fan", "Träumen", "Dream"),
    ("ตื่น", "tuen", "Wach", "Awake"),
    ("ง่วงนอน", "nguang-non", "Schläfrig", "Sleepy"),
    ("เครียด", "khriat", "Gestresst", "Stressed"),
    ("กังวล", "kang-won", "Besorgt", "Worried"),
    ("สบายใจ", "sa-bai-jai", "Entspannt", "Relaxed"),
    ("หงุดหงิด", "ngut-ngid", "Frustriert", "Frustrated"),
    ("เบื่อ", "buea", "Gelangweilt", "Bored"),
    ("รำคาญ", "ram-khan", "Genervt", "Annoyed"),
    ("ภูมิใจ", "phum-jai", "Stolz", "Proud"),
    ("อิจฉา", "it-cha", "Neidisch", "Jealous"),
    ("อาย", "ai", "Schüchtern/Peinlich", "Shy/Embarrassed"),
    ("กล้า", "kla", "Mutig", "Brave"),
    ("ขี้เกียจ", "khi-kiat", "Faul", "Lazy"),
    ("ขยัน", "kha-yan", "Fleißig", "Diligent"),
    ("ฉลาด", "cha-lat", "Klug", "Smart"),
    ("โง่", "ngo", "Dumm", "Stupid"),
    ("สุภาพ", "su-phap", "Höflich", "Polite"),
    ("หยาบคาย", "yap-khai", "Unhöflich", "Rude"),
    ("ใจดี", "jai-dee", "Herzlich/Gütig", "Kind"),
    ("ใจร้าย", "jai-rai", "Grausam", "Cruel"),
    ("เห็นแก่ตัว", "hen-kae-tua", "Egoistisch", "Selfish"),
    ("เอื้อเฟื้อ", "uea-fuea", "Großzügig", "Generous"),
    ("ซื่อสัตย์", "sue-sat", "Ehrlich", "Honest"),
    ("โกหก", "ko-hok", "Lügen", "Lie"),
    ("ความเชื่อ", "khwam-chuea", "Glaube", "Belief"),
    ("ความคิด", "khwam-khit", "Gedanke", "Thought"),
    ("ความฝัน", "khwam-fan", "Traum", "Dream (Ambition)"),
    ("เป้าหมาย", "pao-mai", "Ziel", "Goal"),
    ("ความสำเร็จ", "khwam-sam-ret", "Erfolg", "Success"),
    ("ความล้มเหลว", "khwam-lom-leo", "Misserfolg", "Failure"),
    ("ปัญหา", "pan-ha", "Problem", "Problem"),
    ("ทางออก", "thang-ok", "Lösung/Ausgang", "Solution/Exit"),
    ("โอกาส", "o-kat", "Gelegenheit", "Opportunity"),
    ("โชคดี", "chok-dee", "Viel Glück", "Good luck"),
    ("โชคร้าย", "chok-rai", "Pech", "Bad luck"),
    ("บังเอิญ", "bang-oen", "Zufällig", "Coincidence"),
    ("ตั้งใจ", "tang-jai", "Absichtlich", "Intentional"),
    ("ตัดสินใจ", "tat-sin-jai", "Entscheiden", "Decide"),
    ("เปลี่ยนใจ", "plian-jai", "Meinung ändern", "Change mind"),
    ("เลือก", "lueak", "Wählen", "Choose"),
    ("ยอมรับ", "yom-rap", "Akzeptieren", "Accept"),
    ("ปฏิเสธ", "pa-ti-set", "Ablehnen", "Refuse"),
    ("ต่อรอง", "tor-rong", "Verhandeln", "Negotiate"),
    ("ตกลง", "tok-long", "Einverstanden", "Agree"),
    ("สัญญา", "san-ya", "Vertrag/Versprechen", "Contract/Promise"),
    ("เซ็น", "sen", "Unterschreiben", "Sign"),
    ("ประชุม", "pra-chum", "Treffen/Meeting", "Meeting"),
    ("นัด", "nat", "Termin", "Appointment"),
    ("เลื่อน", "luean", "Verschieben", "Postpone"),
    ("ยกเลิก", "yok-loek", "Absagen", "Cancel"),
    ("โทรหา", "tho-ha", "Anrufen", "Call"),
    ("รับสาย", "rap-sai", "Abheben", "Answer phone"),
    ("วางสาย", "wang-sai", "Auflegen", "Hang up"),
    ("ฝากข้อความ", "fak-kho-khwam", "Nachricht hinterlassen", "Leave message"),
    ("ส่ง", "song", "Senden", "Send"),
    ("รับ", "rap", "Empfangen", "Receive"),
    ("อีเมล", "i-men", "E-Mail", "Email"),
    ("เว็บไซต์", "wep-sai", "Webseite", "Website"),
    ("แอปพลิเคชัน", "aep-phli-khe-chan", "App", "App"),
    ("ดาวน์โหลด", "dao-lot", "Herunterladen", "Download"),
    ("อัปโหลด", "ap-lot", "Hochladen", "Upload"),
    ("แชร์", "chae", "Teilen", "Share"),
    ("โพสต์", "phot", "Posten", "Post"),
    ("ความคิดเห็น", "khwam-khit-hen", "Kommentar", "Comment"),
    ("ข่าว", "khao", "Nachrichten", "News"),
    ("ข้อมูล", "kho-mun", "Information", "Information"),
    ("รายละเอียด", "ra-ia-la-iat", "Details", "Details"),
    ("เหตุผล", "het-phon", "Grund", "Reason"),
    ("ข้อดี", "kho-dee", "Vorteil", "Advantage"),
    ("ข้อเสีย", "kho-sia", "Nachteil", "Disadvantage"),
    ("เปรียบเทียบ", "priap-thiap", "Vergleichen", "Compare"),
    ("แตกต่าง", "taek-tang", "Anders", "Different"),
    ("เหมือนกัน", "muean-kan", "Gleich", "Same"),
    ("คล้ายกัน", "khlai-kan", "Ähnlich", "Similar"),
    ("ประเภท", "pra-phet", "Kategorie", "Category"),
    ("ชนิด", "cha-nit", "Art", "Type"),
    ("ระดับ", "ra-dap", "Level", "Level"),
    ("สูง", "sung", "Hoch", "High"),
    ("ต่ำ", "tam", "Niedrig", "Low"),
    ("กลาง", "klang", "Mittel", "Middle"),
    ("คุณภาพ", "khun-na-phap", "Qualität", "Quality"),
    ("ราคา", "ra-kha", "Preis", "Price"),
    ("ค่าใช้จ่าย", "kha-chai-jai", "Kosten", "Cost"),
    ("ฟรี", "free", "Kostenlos", "Free"),
    ("เสียเงิน", "sia-ngoen", "Kostenpflichtig", "Paid"),
    ("คุ้มค่า", "khum-kha", "Lohnenswert", "Worth it"),
    ("ประหยัด", "pra-yat", "Sparsam", "Save (money)"),
    ("ฟุ่มเฟือย", "fum-fueai", "Verschwenderisch", "Lavish"),
    ("รวย", "ruay", "Reich", "Rich"),
    ("จน", "jon", "Arm", "Poor"),
    ("หนี้", "nee", "Schulden", "Debt"),
    ("ยืม", "yuem", "Leihen", "Borrow"),
    ("คืนเงิน", "khuen-ngoen", "Geld zurück", "Refund"),
    ("เงินสด", "ngoen-sot", "Bargeld", "Cash"),
    ("บัตรเครดิต", "bat-khre-dit", "Kreditkarte", "Credit card"),
    ("โอนเงิน", "on-ngoen", "Überweisen", "Transfer money"),
    ("ถอนเงิน", "thon-ngoen", "Abheben", "Withdraw"),
    ("ฝากเงิน", "fak-ngoen", "Einzahlen", "Deposit"),
    ("บัญชี", "ban-chee", "Konto", "Account"),
    ("ภาษี", "pha-see", "Steuer", "Tax"),
    ("ใบเสร็จ", "bai-set", "Quittung", "Receipt"),
    ("ลดราคา", "lot-ra-kha", "Rabatt", "Discount"),
    ("โปรโมชั่น", "pro-mo-chan", "Promotion", "Promotion"),
    ("โฆษณา", "kho-sa-na", "Werbung", "Advertisement"),
    ("ลูกค้า", "luk-kha", "Kunde", "Customer"),
    ("คนขาย", "khon-khai", "Verkäufer", "Seller"),
    ("บริการ", "bo-ri-kan", "Service", "Service"),
    ("ประทับใจ", "pra-thap-jai", "Beeindruckt", "Impressed"),
    ("ผิดหวัง", "phit-wang", "Enttäuscht", "Disappointed"),
    ("แนะนำ", "nae-nam", "Empfehlen", "Recommend"),
    ("บอกต่อ", "bok-tor", "Weitererzählen", "Tell others"),
    ("รีวิว", "ri-wio", "Bewertung", "Review"),
    ("คะแนน", "kha-naen", "Punkte", "Score"),
    ("อันดับ", "an-dap", "Rang", "Rank"),
    ("ชนะ", "cha-na", "Gewinnen", "Win"),
    ("แพ้", "phae", "Verlieren", "Lose"),
    ("เสมอ", "sa-moe", "Unentschieden", "Draw"),
    ("การแข่งขัน", "kan-khaeng-khan", "Wettbewerb", "Competition"),
    ("รางวัล", "rang-wan", "Preis (Award)", "Prize"),
    ("ของขวัญ", "khong-khwan", "Geschenk", "Gift"),
    ("เซอร์ไพรส์", "soe-phrai", "Überraschung", "Surprise"),
    ("ฉลอง", "cha-long", "Feiern", "Celebrate"),
    ("ปาร์ตี้", "pa-tee", "Party", "Party"),
    ("วันเกิด", "wan-koet", "Geburtstag", "Birthday"),
    ("แต่งงาน", "taeng-ngan", "Hochzeit", "Wedding"),
    ("หย่า", "ya", "Scheidung", "Divorce"),
    ("โสด", "sot", "Single", "Single"),
    ("มีแฟนแล้ว", "mee-faen-laeo", "Vergeben", "Taken"),
    ("ความสัมพันธ์", "khwam-sam-phan", "Beziehung", "Relationship"),
    ("รัก", "rak", "Liebe", "Love"),
    ("เลิก", "loek", "Trennen", "Break up"),
    ("คิดถึง", "khit-thueng", "Vermissen", "Miss"),
    ("ดูแล", "du-lae", "Kümmern", "Take care"),
    ("ห่วง", "huang", "Sorgen machen", "Worry"),
    ("ไว้ใจ", "wai-jai", "Vertrauen", "Trust"),
    ("เข้าใจผิด", "khao-jai-phit", "Missverstehen", "Misunderstand"),
    ("ทะเลาะ", "tha-lo", "Streiten", "Argue"),
    ("ดีกัน", "dee-kan", "Versöhnen", "Make up"),
    ("ขอโทษ", "kho-thot", "Entschuldigen", "Apologize"),
    ("ให้อภัย", "hai-a-phai", "Vergeben", "Forgive"),
    ("ขอบคุณ", "khop-khun", "Danken", "Thank"),
    ("ยินดี", "yin-dee", "Gern geschehen/Erfreut", "Pleasure"),
    ("เกรงใจ", "kreng-jai", "Rücksicht nehmen", "Considerate")
]

# B2 (200 words)
b2_list = [
    ("การเมือง", "kan-mueang", "Politik", "Politics"),
    ("รัฐบาล", "rat-tha-ban", "Regierung", "Government"),
    ("นายกรัฐมนตรี", "na-yok-rat-tha-mon-tri", "Premierminister", "Prime Minister"),
    ("กฎหมาย", "kot-mai", "Gesetz", "Law"),
    ("สิทธิ", "sit-thi", "Recht (Anspruch)", "Right"),
    ("หน้าที่", "na-thee", "Pflicht/Aufgabe", "Duty"),
    ("ประชาธิปไตย", "pra-cha-thi-pa-tai", "Demokratie", "Democracy"),
    ("การเลือกตั้ง", "kan-lueak-tang", "Wahl", "Election"),
    ("เศรษฐกิจ", "set-tha-kit", "Wirtschaft", "Economy"),
    ("การค้า", "kan-kha", "Handel", "Trade"),
    ("การลงทุน", "kan-long-thun", "Investition", "Investment"),
    ("ตลาดหุ้น", "ta-lat-hun", "Börse", "Stock market"),
    ("บริษัท", "bo-ri-sat", "Firma", "Company"),
    ("ธุรกิจ", "thu-ra-kit", "Geschäft", "Business"),
    ("ลูกจ้าง", "luk-jang", "Angestellter", "Employee"),
    ("เจ้านาย", "jao-nai", "Chef", "Boss"),
    ("เงินเดือน", "ngoen-duean", "Gehalt", "Salary"),
    ("โบนัส", "bo-nat", "Bonus", "Bonus"),
    ("ตกงาน", "tok-ngan", "Arbeitslos", "Unemployed"),
    ("เกษียณ", "ka-sian", "Ruhestand", "Retire"),
    ("สังคม", "sang-khom", "Gesellschaft", "Society"),
    ("ชุมชน", "chum-chon", "Gemeinschaft", "Community"),
    ("สิ่งแวดล้อม", "sing-waet-lom", "Umwelt", "Environment"),
    ("มลพิษ", "mon-la-phit", "Verschmutzung", "Pollution"),
    ("ขยะ", "kha-ya", "Müll", "Garbage"),
    ("รีไซเคิล", "ri-sai-khel", "Recycling", "Recycle"),
    ("ภาวะโลกร้อน", "pha-wa-lok-ron", "Erderwärmung", "Global warming"),
    ("พลังงาน", "pha-lang-ngan", "Energie", "Energy"),
    ("ประหยัด", "pra-yat", "Sparen", "Save"),
    ("ทรัพยากร", "sap-pha-ya-kon", "Ressource", "Resource"),
    ("วิทยาศาสตร์", "wit-tha-ya-sat", "Wissenschaft", "Science"),
    ("เทคโนโลยี", "thek-no-lo-yi", "Technologie", "Technology"),
    ("คอมพิวเตอร์", "khom-phiu-toe", "Computer", "Computer"),
    ("โปรแกรม", "pro-kraem", "Programm", "Program"),
    ("พัฒนา", "phat-tha-na", "Entwickeln", "Develop"),
    ("วิจัย", "wi-jai", "Forschen", "Research"),
    ("ทดลอง", "thot-long", "Experimentieren", "Experiment"),
    ("ค้นพบ", "khon-phop", "Entdecken", "Discover"),
    ("ประดิษฐ์", "pra-dit", "Erfinden", "Invent"),
    ("ทันสมัย", "than-sa-mai", "Modern", "Modern"),
    ("โบราณ", "bo-ran", "Antik/Alt", "Ancient"),
    ("สื่อสาร", "sue-san", "Kommunizieren", "Communicate"),
    ("ข้อมูล", "kho-mun", "Daten", "Data"),
    ("ความรู้", "khwam-ru", "Wissen", "Knowledge"),
    ("การศึกษา", "kan-suek-sa", "Bildung", "Education"),
    ("มหาวิทยาลัย", "ma-ha-wit-tha-ya-lai", "Universität", "University"),
    ("คณะ", "kha-na", "Fakultät", "Faculty"),
    ("วิชา", "wi-cha", "Fach", "Subject"),
    ("สอบ", "sop", "Prüfung", "Exam"),
    ("เกรด", "kret", "Note", "Grade"),
    ("ทุนการศึกษา", "thun-kan-suek-sa", "Stipendium", "Scholarship"),
    ("ปริญญา", "pa-rin-ya", "Abschluss/Grad", "Degree"),
    ("สุขภาพ", "suk-kha-phap", "Gesundheit", "Health"),
    ("โรค", "rok", "Krankheit", "Disease"),
    ("อาการ", "a-kan", "Symptom", "Symptom"),
    ("รักษา", "rak-sa", "Behandeln", "Treat/Cure"),
    ("หาย", "hai", "Genesen", "Recover"),
    ("ป้องกัน", "pong-kan", "Verhindern", "Prevent"),
    ("ระบาด", "ra-bat", "Ausbreiten (Krankheit)", "Epidemic"),
    ("วัคซีน", "wak-sin", "Impfstoff", "Vaccine"),
    ("ผ่าตัด", "pha-tat", "Operation", "Surgery"),
    ("บริจาค", "bo-ri-jak", "Spenden", "Donate"),
    ("อุบัติเหตุ", "u-bat-ti-het", "Unfall", "Accident"),
    ("ฉุกเฉิน", "chuk-choen", "Notfall", "Emergency"),
    ("ตำรวจ", "tam-ruat", "Polizei", "Police"),
    ("จับกุม", "jap-kum", "Verhaften", "Arrest"),
    ("ขโมย", "kha-moi", "Dieb/Stehlen", "Thief/Steal"),
    ("อาชญากรรม", "at-ya-kam", "Verbrechen", "Crime"),
    ("ศาล", "san", "Gericht", "Court"),
    ("พยาน", "pha-yan", "Zeuge", "Witness"),
    ("ตัดสิน", "tat-sin", "Urteilen", "Judge"),
    ("จำคุก", "jam-khuk", "Gefängnis", "Imprison"),
    ("ความรุนแรง", "khwam-run-raeng", "Gewalt", "Violence"),
    ("สงคราม", "song-khram", "Krieg", "War"),
    ("สันติภาพ", "san-ti-phap", "Frieden", "Peace"),
    ("กองทัพ", "kong-thap", "Armee", "Army"),
    ("ทหาร", "tha-han", "Soldat", "Soldier"),
    ("อาวุธ", "a-wut", "Waffe", "Weapon"),
    ("ระเบิด", "ra-boet", "Bombe/Explodieren", "Bomb/Explode"),
    ("ป้องกันตัว", "pong-kan-tua", "Selbstverteidigung", "Self-defense"),
    ("ช่วยเหลือ", "chuay-luea", "Helfen/Retten", "Rescue"),
    ("ภัยธรรมชาติ", "phai-tham-ma-chat", "Naturkatastrophe", "Natural disaster"),
    ("น้ำท่วม", "nam-thuam", "Flut", "Flood"),
    ("แผ่นดินไหว", "phaen-din-wai", "Erdbeben", "Earthquake"),
    ("ไฟไหม้", "fai-mai", "Feuer", "Fire"),
    ("พายุ", "pha-yu", "Sturm", "Storm"),
    ("อากาศ", "a-kat", "Wetter/Luft", "Weather/Air"),
    ("อุณหภูมิ", "un-ha-phum", "Temperatur", "Temperature"),
    ("ความชื้น", "khwam-chuen", "Feuchtigkeit", "Humidity"),
    ("ฤดูกาล", "rue-du-kan", "Jahreszeit", "Season"),
    ("เปลี่ยนแปลง", "plian-plaeng", "Verändern", "Change"),
    ("กระทบ", "kra-thop", "Auswirken", "Affect"),
    ("ผลลัพธ์", "phon-lap", "Ergebnis", "Result"),
    ("สาเหตุ", "sa-het", "Ursache", "Cause"),
    ("แก้ไข", "kae-khai", "Korrigieren/Lösen", "Solve/Fix"),
    ("ปรับปรุง", "prap-prung", "Verbessern", "Improve"),
    ("สถานการณ์", "sa-tha-na-kan", "Situation", "Situation"),
    ("วิกฤต", "wi-krit", "Krise", "Crisis"),
    ("โอกาส", "o-kat", "Chance", "Chance"),
    ("ท้าทาย", "tha-thai", "Herausforderung", "Challenge"),
    ("เสี่ยง", "siang", "Risiko", "Risk"),
    ("ตัดสินใจ", "tat-sin-jai", "Entscheiden", "Decide"),
    ("วางแผน", "wang-phaen", "Planen", "Plan"),
    ("เป้าหมาย", "pao-mai", "Ziel", "Goal"),
    ("อนาคต", "a-na-khot", "Zukunft", "Future"),
    ("ปัจจุบัน", "pat-ju-ban", "Gegenwart", "Present"),
    ("อดีต", "a-deet", "Vergangenheit", "Past"),
    ("ประวัติศาสตร์", "pra-wat-sat", "Geschichte", "History"),
    ("วัฒนธรรม", "wat-tha-na-tham", "Kultur", "Culture"),
    ("ศิลปะ", "sin-la-pa", "Kunst", "Art"),
    ("ดนตรี", "don-tri", "Musik", "Music"),
    ("วรรณกรรม", "wan-na-kam", "Literatur", "Literature"),
    ("กวี", "ka-wee", "Dichter", "Poet"),
    ("บทความ", "bot-khwam", "Artikel", "Article"),
    ("หนังสือพิมพ์", "nang-sue-phim", "Zeitung", "Newspaper"),
    ("นิตยสาร", "nit-ta-ya-san", "Magazin", "Magazine"),
    ("รายการ", "rai-kan", "Sendung/Liste", "Program/List"),
    ("วิทยุ", "wit-tha-yu", "Radio", "Radio"),
    ("โทรทัศน์", "tho-ra-that", "Fernseher", "Television"),
    ("อินเทอร์เน็ต", "in-thoe-net", "Internet", "Internet"),
    ("โซเชียล", "so-chian", "Soziale Medien", "Social Media"),
    ("แสดงความคิดเห็น", "sa-daeng-khwam-khit-hen", "Kommentieren", "Comment"),
    ("ติดตาม", "tit-tam", "Folgen", "Follow"),
    ("กดไลค์", "kot-lai", "Liken", "Like"),
    ("บล็อก", "blok", "Blockieren", "Block"),
    ("ค้นหา", "khon-ha", "Suchen", "Search"),
    ("ข้อมูล", "kho-mun", "Information", "Information"),
    ("เชื่อถือได้", "chuea-thue-dai", "Zuverlässig", "Reliable"),
    ("ข่าวปลอม", "khao-plom", "Fake News", "Fake News"),
    ("ความจริง", "khwam-jing", "Wahrheit", "Truth"),
    ("เท็จ", "thet", "Falsch (Unwahr)", "False"),
    ("โกหก", "ko-hok", "Lügen", "Lie"),
    ("หลอกลวง", "lok-luang", "Betrügen", "Deceive"),
    ("สุจริต", "sut-ja-rit", "Ehrlich", "Honest"),
    ("ยุติธรรม", "yut-ti-tham", "Gerecht", "Fair"),
    ("ลำเอียง", "lam-iang", "Voreingenommen", "Biased"),
    ("วิจารณ์", "wi-jan", "Kritisieren", "Criticize"),
    ("ชมเชย", "chom-choei", "Loben", "Praise"),
    ("สนับสนุน", "sa-nap-sa-nun", "Unterstützen", "Support"),
    ("คัดค้าน", "khat-khan", "Ablehnen/Dagegen sein", "Oppose"),
    ("เห็นด้วย", "hen-duay", "Zustimmen", "Agree"),
    ("ไม่เห็นด้วย", "mai-hen-duay", "Nicht zustimmen", "Disagree"),
    ("ข้อเสนอ", "kho-sa-noe", "Vorschlag", "Proposal"),
    ("ทางเลือก", "thang-lueak", "Option", "Option"),
    ("ตัดสินใจ", "tat-sin-jai", "Entscheiden", "Decide"),
    ("ลังเล", "lang-le", "Zögern", "Hesitate"),
    ("มั่นใจ", "man-jai", "Selbstbewusst", "Confident"),
    ("กังวล", "kang-won", "Besorgt", "Worried"),
    ("กลัว", "klua", "Angst", "Fear"),
    ("เกลียด", "kliat", "Hassen", "Hate"),
    ("รัก", "rak", "Lieben", "Love"),
    ("ชอบ", "chop", "Mögen", "Like"),
    ("ศรัทธา", "sat-tha", "Glaube", "Faith"),
    ("ศาสนา", "sat-sa-na", "Religion", "Religion"),
    ("ศีลธรรม", "sin-la-tham", "Moral", "Morality"),
    ("จริยธรรม", "ja-ri-ya-tham", "Ethik", "Ethics"),
    ("ความดี", "khwam-dee", "Güte", "Goodness"),
    ("ความชั่ว", "khwam-chua", "Böse", "Evil"),
    ("บาป", "bap", "Sünde", "Sin"),
    ("บุญ", "bun", "Verdienst (Merit)", "Merit"),
    ("สวรรค์", "sa-wan", "Himmel", "Heaven"),
    ("นรก", "na-rok", "Hölle", "Hell"),
    ("วิญญาณ", "win-yan", "Geist/Seele", "Soul/Spirit"),
    ("ผี", "phee", "Geist", "Ghost"),
    ("โชคลาง", "chok-lang", "Aberglaube", "Superstition"),
    ("หมอดู", "mo-du", "Wahrsager", "Fortune teller"),
    ("ดวง", "duang", "Schicksal", "Horoscope/Destiny"),
    ("แก้บน", "kae-bon", "Gelübde einlösen", "Fulfill vow"),
    ("สิ่งศักดิ์สิทธิ์", "sing-sak-sit", "Heiliges", "Sacred things"),
    ("เคารพ", "khao-rop", "Respektieren", "Respect"),
    ("ดูถูก", "du-thuk", "Beleidigen/Herabsehen", "Insult"),
    ("ประมาท", "pra-mat", "Nachlässig", "Careless"),
    ("รอบคอบ", "rop-khop", "Vorsichtig/Umsichtig", "Prudent"),
    ("ข้อตกลง", "kho-tok-long", "Abkommen", "Agreement")
]

# C2 (200 words)
c2_list = [
    ("ปรัชญาเมธี", "prat-ya-me-thee", "Philosoph", "Philosopher"),
    ("ตรรกศาสตร์", "tak-ka-sat", "Logik", "Logic"),
    ("อภิปรัชญา", "a-phi-prat-ya", "Metaphysik", "Metaphysics"),
    ("สุนทรียศาสตร์", "sun-tha-ree-ya-sat", "Ästhetik", "Aesthetics"),
    ("จริยธรรม", "ja-ri-ya-tham", "Ethik", "Ethics"),
    ("ญาณวิทยา", "yan-na-wit-tha-ya", "Erkenntnistheorie", "Epistemology"),
    ("ปรากฏการณ์วิทยา", "pra-kot-kan-wit-tha-ya", "Phänomenologie", "Phenomenology"),
    ("อัตภาวะนิยม", "at-ta-pha-wa-ni-yom", "Existentialismus", "Existentialism"),
    ("โครงสร้างนิยม", "khrong-sang-ni-yom", "Strukturalismus", "Structuralism"),
    ("หลังสมัยใหม่นิยม", "lang-sa-mai-mai-ni-yom", "Postmoderne", "Postmodernism"),
    ("วาทกรรม", "wa-tha-kam", "Diskurs", "Discourse"),
    ("บริบท", "bo-ri-bot", "Kontext", "Context"),
    ("นัยยะ", "nai-ya", "Implikation", "Implication"),
    ("อุปมาอุปไมย", "up-pa-ma-up-pa-mai", "Analogie", "Analogy"),
    ("สัญลักษณ์", "san-ya-lak", "Symbol", "Symbol"),
    ("สัญญาณ", "san-yan", "Zeichen", "Sign"),
    ("ความหมาย", "khwam-mai", "Bedeutung", "Meaning"),
    ("การตีความ", "kan-tee-khwam", "Interpretation", "Interpretation"),
    ("วิจารณญาณ", "wi-ja-ra-na-yan", "Urteilsvermögen", "Judgement"),
    ("ปัญญา", "pan-ya", "Weisheit/Intellekt", "Wisdom/Intellect"),
    ("สติปัญญา", "sa-ti-pan-ya", "Intelligenz", "Intelligence"),
    ("ไหวพริบ", "wai-phrip", "Scharfsinn", "Wit"),
    ("ปฏิภาณ", "pa-ti-phan", "Schlagfertigkeit", "Wit/Improvisation"),
    ("อัจฉริยะ", "at-cha-ri-ya", "Genie", "Genius"),
    ("ปราชญ์", "prat", "Gelehrter", "Scholar"),
    ("ผู้รู้", "phu-ru", "Kenner", "Connoisseur"),
    ("ผู้เชี่ยวชาญ", "phu-chiao-chan", "Experte", "Expert"),
    ("นักวิชาการ", "nak-wi-cha-kan", "Akademiker", "Academic"),
    ("วิทยานิพนธ์", "wit-tha-ya-ni-phon", "Dissertation", "Thesis"),
    ("งานวิจัย", "ngan-wi-jai", "Forschung", "Research"),
    ("ระเบียบวิธีวิจัย", "ra-biap-wi-thee-wi-jai", "Forschungsmethodik", "Research Methodology"),
    ("สมมติฐาน", "som-mot-ti-than", "Hypothese", "Hypothesis"),
    ("ทฤษฎีบท", "thrit-sa-dee-bot", "Theorem", "Theorem"),
    ("สัจพจน์", "sat-ja-phot", "Axiom", "Axiom"),
    ("บทพิสูจน์", "bot-phi-sut", "Beweis (Math/Logic)", "Proof"),
    ("ข้อเท็จจริง", "kho-thet-jing", "Fakt", "Fact"),
    ("หลักฐาน", "lak-than", "Beweis (Material)", "Evidence"),
    ("ข้อมูลเชิงประจักษ์", "kho-mun-choeng-pra-jak", "Empirische Daten", "Empirical Data"),
    ("อคติ", "a-kha-ti", "Voreingenommenheit", "Bias"),
    ("ความน่าจะเป็น", "khwam-na-ja-pen", "Wahrscheinlichkeit", "Probability"),
    ("ความเสี่ยง", "khwam-siang", "Risiko", "Risk"),
    ("ความไม่แน่นอน", "khwam-mai-nae-non", "Unsicherheit", "Uncertainty"),
    ("ความซับซ้อน", "khwam-sap-son", "Komplexität", "Complexity"),
    ("ความโกลาหล", "khwam-ko-la-hon", "Chaos", "Chaos"),
    ("ระเบียบ", "ra-biap", "Ordnung", "Order"),
    ("ระบบนิเวศ", "ra-bop-ni-wet", "Ökosystem", "Ecosystem"),
    ("วิวัฒนาการ", "wi-wat-tha-na-kan", "Evolution", "Evolution"),
    ("พันธุกรรม", "phan-thu-kam", "Genetik", "Genetics"),
    ("ชีวภาพ", "chee-wa-phap", "Biologisch", "Biological"),
    ("กายภาพ", "kai-ya-phap", "Physisch", "Physical"),
    ("เคมี", "khe-mee", "Chemisch", "Chemical"),
    ("ดาราศาสตร์", "da-ra-sat", "Astronomie", "Astronomy"),
    ("จักรวาล", "jak-kra-wan", "Universum", "Universe"),
    ("มิติ", "mi-ti", "Dimension", "Dimension"),
    ("เวลา", "we-la", "Zeit", "Time"),
    ("อวกาศ", "a-wa-kat", "Raum/Space", "Space"),
    ("แรงโน้มถ่วง", "raeng-nom-thuang", "Schwerkraft", "Gravity"),
    ("อนุภาค", "a-nu-phak", "Teilchen", "Particle"),
    ("อะตอม", "a-tom", "Atom", "Atom"),
    ("ควอนตัม", "khwon-tam", "Quanten", "Quantum"),
    ("พลังงานนิวเคลียร์", "pha-lang-ngan-niu-khlia", "Kernenergie", "Nuclear Energy"),
    ("กัมมันตภาพรังสี", "kam-man-ta-phap-rang-see", "Radioaktivität", "Radioactivity"),
    ("ปฏิกิริยา", "pa-ti-ki-ri-ya", "Reaktion", "Reaction"),
    ("สังเคราะห์", "sang-khro", "Synthetisieren", "Synthesize"),
    ("สลายตัว", "sa-lai-tua", "Zerfallen", "Decay"),
    ("ระเหย", "ra-hoei", "Verdampfen", "Evaporate"),
    ("ควบแน่น", "khuap-naen", "Kondensieren", "Condense"),
    ("ละลาย", "la-lai", "Schmelzen/Lösen", "Melt/Dissolve"),
    ("แข็งตัว", "khaeng-tua", "Erstarren", "Freeze/Solidify"),
    ("ตกผลึก", "tok-pha-luek", "Kristallisieren", "Crystallize"),
    ("ระเหิด", "ra-hoet", "Sublimieren", "Sublimate"),
    ("การเปลี่ยนแปลงภูมิอากาศ", "kan-plian-plaeng-phum-mi-a-kat", "Klimawandel", "Climate Change"),
    ("นโยบายสาธารณะ", "na-yo-bai-sa-tha-ra-na", "Öffentliche Politik", "Public Policy"),
    ("สวัสดิการสังคม", "sa-wat-di-kan-sang-khom", "Sozialhilfe", "Social Welfare"),
    ("ประกันสังคม", "pra-kan-sang-khom", "Sozialversicherung", "Social Security"),
    ("หลักประกันสุขภาพ", "lak-pra-kan-suk-kha-phap", "Krankenversicherung", "Health Security"),
    ("สิทธิมนุษยชน", "sit-thi-ma-nut-sa-ya-chon", "Menschenrechte", "Human Rights"),
    ("เสรีภาพในการแสดงออก", "se-ri-phap-nai-kan-sa-daeng-ok", "Meinungsfreiheit", "Freedom of Expression"),
    ("ความเป็นธรรม", "khwam-pen-tham", "Gerechtigkeit (Fairness)", "Fairness"),
    ("ความเสมอภาค", "khwam-sa-moe-phak", "Gleichheit", "Equality"),
    ("การเลือกปฏิบัติ", "kan-lueak-pa-ti-bat", "Diskriminierung", "Discrimination"),
    ("อคติทางเพศ", "a-kha-ti-thang-phet", "Sexismus", "Sexism"),
    ("การเหยียดเชื้อชาติ", "kan-yiat-chuea-chat", "Rassismus", "Racism"),
    ("ความหลากหลาย", "khwam-lak-lai", "Vielfalt", "Diversity"),
    ("พหุวัฒนธรรม", "pha-hu-wat-tha-na-tham", "Multikulturalismus", "Multiculturalism"),
    ("โลกาภิวัตน์", "lo-ka-phi-wat", "Globalisierung", "Globalization"),
    ("ท้องถิ่นนิยม", "thong-thin-ni-yom", "Lokalismus", "Localism"),
    ("ชาตินิยม", "chat-ni-yom", "Nationalismus", "Nationalism"),
    ("เสรีนิยม", "se-ri-ni-yom", "Liberalismus", "Liberalism"),
    ("อนุรักษ์นิยม", "a-nu-rak-ni-yom", "Konservatismus", "Conservatism"),
    ("สังคมนิยม", "sang-khom-ni-yom", "Sozialismus", "Socialism"),
    ("คอมมิวนิสต์", "khom-miu-nit", "Kommunismus", "Communism"),
    ("ทุนนิยม", "thun-ni-yom", "Kapitalismus", "Capitalism"),
    ("เผด็จการ", "pha-det-kan", "Diktatur", "Dictatorship"),
    ("อำนาจนิยม", "am-nat-ni-yom", "Autoritarismus", "Authoritarianism"),
    ("รัฐประหาร", "rat-tha-pra-han", "Staatsstreich", "Coup d'etat"),
    ("การปฏิวัติ", "kan-pa-ti-wat", "Revolution", "Revolution"),
    ("การจลาจล", "kan-ja-la-jon", "Aufstand/Unruhen", "Riot"),
    ("สงครามกลางเมือง", "song-khram-klang-mueang", "Bürgerkrieg", "Civil War"),
    ("การก่อการร้าย", "kan-ko-kan-rai", "Terrorismus", "Terrorism"),
    ("ความมั่นคงแห่งชาติ", "khwam-man-khong-haeng-chat", "Nationale Sicherheit", "National Security"),
    ("นโยบายต่างประเทศ", "na-yo-bai-tang-pra-thet", "Außenpolitik", "Foreign Policy"),
    ("ความสัมพันธ์ระหว่างประเทศ", "khwam-sam-phan-ra-wang-pra-thet", "Internationale Beziehungen", "International Relations"),
    ("องค์กรระหว่างประเทศ", "ong-kon-ra-wang-pra-thet", "Internationale Org.", "International Org."),
    ("สหประชาชาติ", "sa-ha-pra-cha-chat", "Vereinte Nationen", "United Nations"),
    ("สนธิสัญญา", "son-thi-san-ya", "Vertrag (Völkerrecht)", "Treaty"),
    ("อนุสัญญา", "a-nu-san-ya", "Konvention", "Convention"),
    ("พิธีสาร", "phi-thee-san", "Protokoll", "Protocol"),
    ("ข้อตกลงการค้าเสรี", "kho-tok-long-kan-kha-se-ri", "Freihandelsabkommen", "Free Trade Agreement"),
    ("กำแพงภาษี", "kam-phaeng-pha-see", "Zollmauer", "Tariff Barrier"),
    ("การกีดกันทางการค้า", "kan-keet-kan-thang-kan-kha", "Handelsprotektionismus", "Trade Protectionism"),
    ("ดุลการค้า", "dun-kan-kha", "Handelsbilanz", "Trade Balance"),
    ("อัตราแลกเปลี่ยน", "at-tra-laek-plian", "Wechselkurs", "Exchange Rate"),
    ("เงินตราต่างประเทศ", "ngoen-tra-tang-pra-thet", "Devisen", "Foreign Currency"),
    ("หนี้สาธารณะ", "nee-sa-tha-ra-na", "Staatsverschuldung", "Public Debt"),
    ("นโยบายการเงิน", "na-yo-bai-kan-ngoen", "Geldpolitik", "Monetary Policy"),
    ("นโยบายการคลัง", "na-yo-bai-kan-khlang", "Fiskalpolitik", "Fiscal Policy"),
    ("ธนาคารกลาง", "tha-na-khan-klang", "Zentralbank", "Central Bank"),
    ("อัตราดอกเบี้ย", "at-tra-dok-bia", "Zinssatz", "Interest Rate"),
    ("ภาวะเศรษฐกิจถดถอย", "pha-wa-set-tha-kit-thot-thoi", "Rezession", "Recession"),
    ("วิกฤตเศรษฐกิจ", "wi-krit-set-tha-kit", "Wirtschaftskrise", "Economic Crisis"),
    ("ความเหลื่อมล้ำ", "khwam-lueam-lam", "Ungleichheit", "Inequality"),
    ("การกระจายรายได้", "kan-kra-jai-rai-dai", "Einkommensverteilung", "Income Distribution"),
    ("ความยากจน", "khwam-yak-jon", "Armut", "Poverty"),
    ("การพัฒนาที่ยั่งยืน", "kan-phat-tha-na-thi-yang-yuen", "Nachhaltige Entwicklung", "Sustainable Development"),
    ("พลังงานทดแทน", "pha-lang-ngan-thot-thaen", "Erneuerbare Energie", "Renewable Energy"),
    ("คาร์บอนฟุตพริ้นท์", "kha-bon-fut-print", "CO2-Fußabdruck", "Carbon Footprint"),
    ("ก๊าซเรือนกระจก", "kat-ruean-kra-jok", "Treibhausgas", "Greenhouse Gas"),
    ("ความรับผิดชอบต่อสังคม", "khwam-rap-phit-chop-tor-sang-khom", "CSR", "CSR"),
    ("จรรยาบรรณ", "jan-ya-ban", "Ethikkodex", "Code of Ethics"),
    ("ธรรมาภิบาล", "tham-ma-phi-ban", "Good Governance", "Good Governance"),
    ("ความโปร่งใส", "khwam-prong-sai", "Transparenz", "Transparency"),
    ("การทุจริต", "kan-thut-ja-rit", "Korruption", "Corruption"),
    ("การคอร์รัปชัน", "kan-kho-rap-chan", "Korruption", "Corruption"),
    ("สินบน", "sin-bon", "Bestechungsgeld", "Bribe"),
    ("การฟอกเงิน", "kan-fok-ngoen", "Geldwäsche", "Money Laundering"),
    ("กฎหมายอาญา", "kot-mai-a-ya", "Strafrecht", "Criminal Law"),
    ("กฎหมายแพ่ง", "kot-mai-phaeng", "Zivilrecht", "Civil Law"),
    ("ทนายความ", "tha-nai-khwam", "Rechtsanwalt", "Lawyer"),
    ("อัยการ", "ai-ya-kan", "Staatsanwalt", "Prosecutor"),
    ("ผู้พิพากษา", "phu-phi-phak-sa", "Richter", "Judge"),
    ("จำเลย", "jam-loei", "Angeklagter", "Defendant"),
    ("โจทก์", "jot", "Kläger", "Plaintiff"),
    ("คำพิพากษา", "kham-phi-phak-sa", "Urteil", "Judgment"),
    ("อุทธรณ์", "ut-thon", "Berufung", "Appeal"),
    ("ฎีกา", "dee-ka", "Revision", "Supreme Court Appeal"),
    ("รัฐธรรมนูญ", "rat-tha-tham-ma-nun", "Verfassung", "Constitution"),
    ("สภานิติบัญญัติ", "sa-pha-ni-ti-ban-yat", "Legislative", "Legislature"),
    ("ฝ่ายบริหาร", "fai-bo-ri-han", "Exekutive", "Executive"),
    ("ฝ่ายตุลาการ", "fai-tu-la-kan", "Judikative", "Judiciary"),
    ("อำนาจอธิปไตย", "am-nat-a-thi-pa-tai", "Souveränität", "Sovereignty"),
    ("เอกราช", "ek-ka-rat", "Unabhängigkeit", "Independence"),
    ("บูรณภาพแห่งดินแดน", "bu-ra-na-phap-haeng-din-daen", "Territoriale Integrität", "Territorial Integrity"),
    ("ความมั่นคงของมนุษย์", "khwam-man-khong-khong-ma-nut", "Menschliche Sicherheit", "Human Security"),
    ("คุณภาพชีวิต", "khun-na-phap-chee-wit", "Lebensqualität", "Quality of Life"),
    ("ดัชนีความสุข", "dat-cha-nee-khwam-suk", "Glücksindex", "Happiness Index"),
    ("ความพึงพอใจ", "khwam-phueng-pho-jai", "Zufriedenheit", "Satisfaction"),
    ("แรงจูงใจ", "raeng-jung-jai", "Motivation", "Motivation"),
    ("ภาวะผู้นำ", "pha-wa-phu-nam", "Führung", "Leadership"),
    ("การทำงานเป็นทีม", "kan-tham-ngan-pen-team", "Teamarbeit", "Teamwork"),
    ("การแก้ปัญหา", "kan-kae-pan-ha", "Problemlösung", "Problem Solving"),
    ("การตัดสินใจ", "kan-tat-sin-jai", "Entscheidungsfindung", "Decision Making"),
    ("การบริหารไวล", "kan-bo-ri-han-we-la", "Zeitmanagement", "Time Management"),
    ("การสื่อสารที่มีประสิทธิภาพ", "kan-sue-san-thi-mee-pra-sit-thi-phap", "Effektive Kom.", "Effective Communication"),
    ("ทักษะการเจรจาต่อรอง", "thak-sa-kan-jen-ra-ja-tor-rong", "Verhandlungsgeschick", "Negotiation Skills"),
    ("ความคิดสร้างสรรค์", "khwam-khit-sang-san", "Kreativität", "Creativity"),
    ("นวัตกรรม", "na-wat-ta-kam", "Innovation", "Innovation"),
    ("เทคโนโลยีดิสรัปทีฟ", "thek-no-lo-yi-dis-rap-thip", "Disruptive Tech", "Disruptive Tech"),
    ("ปัญญาประดิษฐ์", "pan-ya-pra-dit", "Künstliche Intelligenz", "Artificial Intelligence"),
    ("การเรียนรู้ของเครื่อง", "kan-rian-ru-khong-khrueang", "Maschinelles Lernen", "Machine Learning"),
    ("ข้อมูลขนาดใหญ่", "kho-mun-kha-nat-yai", "Big Data", "Big Data"),
    ("การเข้ารหัส", "kan-khao-ra-hat", "Verschlüsselung", "Encryption"),
    ("ความปลอดภัยทางไซเบอร์", "khwam-plot-phai-thang-sai-boe", "Cybersicherheit", "Cybersecurity"),
    ("การโจรกรรมข้อมูล", "kan-jo-ra-kam-kho-mun", "Datendiebstahl", "Data Theft")
]


# C1 (200 words)
c1_list = [
    ("ปรัชญา", "prat-ya", "Philosophie", "Philosophy"),
    ("อุดมคติ", "u-dom-kha-ti", "Ideal", "Ideal"),
    ("ทัศนคติ", "that-sa-na-kha-ti", "Einstellung (Haltung)", "Attitude"),
    ("วิสัยทัศน์", "wi-sai-that", "Vision", "Vision"),
    ("พันธกิจ", "phan-tha-kit", "Mission", "Mission"),
    ("กลยุทธ์", "kon-la-yut", "Strategie", "Strategy"),
    ("นโยบาย", "na-yo-bai", "Politik (Policy)", "Policy"),
    ("มาตรการ", "mat-tra-kan", "Maßnahme", "Measure"),
    ("ระเบียบ", "ra-biap", "Ordnung/Regel", "Regulation"),
    ("ข้อบังคับ", "kho-bang-khap", "Vorschrift", "Bylaw"),
    ("ธรรมนูญ", "tham-ma-nun", "Verfassung", "Constitution"),
    ("สถาบัน", "sa-tha-ban", "Institution", "Institution"),
    ("องค์กร", "ong-kon", "Organisation", "Organization"),
    ("มูลนิธิ", "mun-la-ni-thi", "Stiftung", "Foundation"),
    ("สมาคม", "sa-ma-khom", "Verband", "Association"),
    ("สหภาพ", "sa-ha-phap", "Union", "Union"),
    ("เครือข่าย", "khruea-khai", "Netzwerk", "Network"),
    ("พันธมิตร", "phan-tha-mit", "Allianz", "Alliance"),
    ("คู่แข่ง", "khu-khaeng", "Konkurrent", "Competitor"),
    ("ศัตรู", "sat-tru", "Feind", "Enemy"),
    ("วิกฤตการณ์", "wi-krit-ta-kan", "Krise (Situation)", "Crisis"),
    ("หายนะ", "ha-ya-na", "Katastrophe", "Disaster"),
    ("โศกนาฏกรรม", "sok-ka-nat-ta-kam", "Tragödie", "Tragedy"),
    ("อุบัติภัย", "u-bat-ti-phai", "Unglück", "Calamity"),
    ("ปรากฏการณ์", "pra-kot-kan", "Phänomen", "Phenomenon"),
    ("แนวโน้ม", "naeo-nom", "Trend", "Trend"),
    ("สถิติ", "sa-thi-ti", "Statistik", "Statistics"),
    ("ดัชนี", "dat-cha-nee", "Index", "Index"),
    ("อัตรา", "at-tra", "Rate", "Rate"),
    ("สัดส่วน", "sat-suan", "Anteil/Proportion", "Proportion"),
    ("เปอร์เซ็นต์", "poe-sen", "Prozent", "Percent"),
    ("เฉลี่ย", "cha-lia", "Durchschnitt", "Average"),
    ("มาตรฐาน", "mat-tra-than", "Standard", "Standard"),
    ("เกณฑ์", "ken", "Kriterium", "Criteria"),
    ("ตัวชี้วัด", "tua-chee-wat", "Indikator", "Indicator"),
    ("ประเมิน", "pra-moen", "Bewerten", "Evaluate"),
    ("วิเคราะห์", "wi-khro", "Analysieren", "Analyze"),
    ("สังเคราะห์", "sang-khro", "Synthetisieren", "Synthesize"),
    ("สรุป", "sa-rup", "Zusammenfassen", "Summarize"),
    ("อธิบาย", "a-thi-bai", "Erklären", "Explain"),
    ("ตีความ", "tee-khwam", "Interpretieren", "Interpret"),
    ("เปรียบเปรย", "priap-proei", "Metapher verwenden", "Metaphor"),
    ("สมมติฐาน", "som-mot-ti-than", "Hypothese", "Hypothesis"),
    ("ทฤษฎี", "thrit-sa-dee", "Theorie", "Theory"),
    ("หลักการ", "lak-kan", "Prinzip", "Principle"),
    ("แนวคิด", "naeo-khit", "Konzept", "Concept"),
    ("โครงสร้าง", "khrong-sang", "Struktur", "Structure"),
    ("ระบบ", "ra-bop", "System", "System"),
    ("กระบวนการ", "kra-buan-kan", "Prozess", "Process"),
    ("ขั้นตอน", "khan-ton", "Schritt (Prozedur)", "Step"),
    ("วิธี", "wi-thee", "Methode", "Method"),
    ("เทคนิค", "thek-nik", "Technik", "Technique"),
    ("นวัตกรรม", "na-wat-ta-kam", "Innovation", "Innovation"),
    ("สร้างสรรค์", "sang-san", "Kreativ", "Creative"),
    ("จินตนาการ", "jin-ta-na-kan", "Fantasie", "Imagination"),
    ("แรงบันดาลใจ", "raeng-ban-dan-jai", "Inspiration", "Inspiration"),
    ("อิทธิพล", "it-thi-phon", "Einfluss", "Influence"),
    ("ผลกระทบ", "phon-kra-thop", "Auswirkung", "Impact"),
    ("ประโยชน์", "pra-yot", "Nutzen", "Benefit"),
    ("โทษ", "thot", "Schaden/Strafe", "Penalty/Harm"),
    ("เสถียรภาพ", "sa-thian-ra-phap", "Stabilität", "Stability"),
    ("ความมั่นคง", "khwam-man-khong", "Sicherheit (Security)", "Security"),
    ("ความเป็นส่วนตัว", "khwam-pen-suan-tua", "Privatsphäre", "Privacy"),
    ("ความปลอดภัย", "khwam-plot-phai", "Sicherheit (Safety)", "Safety"),
    ("เสรีภาพ", "se-ri-phap", "Freiheit", "Liberty"),
    ("อิสรภาพ", "it-sa-ra-phap", "Unabhängigkeit", "Freedom"),
    ("ภราดรภาพ", "pha-ra-don-phap", "Brüderlichkeit", "Fraternity"),
    ("ความเท่าเทียม", "khwam-thao-thiam", "Gleichheit", "Equality"),
    ("ความยุติธรรม", "khwam-yut-ti-tham", "Gerechtigkeit", "Justice"),
    ("ความเมตตา", "khwam-met-ta", "Barmherzigkeit", "Mercy"),
    ("ความกรุณา", "khwam-ka-ru-na", "Güte", "Compassion"),
    ("ความอดทน", "khwam-ot-thon", "Geduld", "Patience"),
    ("ความพยายาม", "khwam-pha-ya-yam", "Bemühung", "Effort"),
    ("ความมุ่งมั่น", "khwam-mung-man", "Entschlossenheit", "Determination"),
    ("ความทะเยอทะยาน", "khwam-tha-yoe-tha-yan", "Ehrgeiz", "Ambition"),
    ("ความอ่อนน้อม", "khwam-on-nom", "Bescheidenheit", "Humility"),
    ("ความหยิ่ง", "khwam-ying", "Arroganz", "Arrogance"),
    ("ความโลภ", "khwam-lop", "Gier", "Greed"),
    ("ความโกรธ", "khwam-krot", "Wut", "Anger"),
    ("ความหลง", "khwam-long", "Verblendung", "Delusion"),
    ("ความริษยา", "khwam-rit-sa-ya", "Neid", "Envy"),
    ("ความเกลียดชัง", "khwam-kliat-chang", "Hass", "Hatred"),
    ("ความรัก", "khwam-rak", "Liebe", "Love"),
    ("ความผูกพัน", "khwam-phuk-phan", "Bindung", "Attachment"),
    ("ความสัมพันธ์", "khwam-sam-phan", "Beziehung", "Relationship"),
    ("มิตรภาพ", "mit-tra-phap", "Freundschaft", "Friendship"),
    ("ศัตรู", "sat-tru", "Feind", "Enemy"),
    ("พันธมิตร", "phan-tha-mit", "Alliierter", "Ally"),
    ("คู่กรณี", "khu-ka-ra-ni", "Gegenseite", "Opponent"),
    ("ข้อพิพาท", "kho-phi-phat", "Streitigkeit", "Dispute"),
    ("การเจรจา", "kan-jen-ra-ja", "Verhandlung", "Negotiation"),
    ("การทูต", "kan-thut", "Diplomatie", "Diplomacy"),
    ("ความร่วมมือ", "khwam-ruam-mue", "Zusammenarbeit", "Cooperation"),
    ("การแลกเปลี่ยน", "kan-laek-plian", "Austausch", "Exchange"),
    ("การช่วยเหลือ", "kan-chuay-luea", "Hilfe", "Assistance"),
    ("การกุศล", "kan-ku-son", "Wohltätigkeit", "Charity"),
    ("อาสาสมัคร", "a-sa-sa-mak", "Freiwilliger", "Volunteer"),
    ("เสียสละ", "sia-sa-la", "Opfern", "Sacrifice"),
    ("อุทิศ", "u-thit", "Widmen", "Dedicate"),
    ("บริจาค", "bo-ri-jak", "Spenden", "Donate"),
    ("สนับสนุน", "sa-nap-sa-nun", "Unterstützen", "Support"),
    ("คัดค้าน", "khat-khan", "Opponieren", "Oppose"),
    ("ต่อต้าน", "tor-tan", "Widerstand leisten", "Resist"),
    ("ประท้วง", "pra-thuang", "Protestieren", "Protest"),
    ("ปฏิวัติ", "pa-ti-wat", "Revolutionieren", "Revolution"),
    ("ปฏิรูป", "pa-ti-rup", "Reformieren", "Reform"),
    ("เปลี่ยนแปลง", "plian-plaeng", "Ändern", "Change"),
    ("พัฒนา", "phat-tha-na", "Entwickeln", "Develop"),
    ("เจริญ", "ja-roen", "Gedeihen", "Prosper"),
    ("เสื่อม", "sueam", "Verfallen", "Decay"),
    ("ล่มสลาย", "lom-sa-lai", "Zusammenbrechen", "Collapse"),
    ("ฟื้นฟู", "fuen-fu", "Wiederherstellen", "Restore"),
    ("อนุรักษ์", "a-nu-rak", "Konservieren", "Conserve"),
    ("สืบสาน", "suep-san", "Fortführen", "Continue (Legacy)"),
    ("เผยแพร่", "phoei-phrae", "Verbreiten", "Disseminate"),
    ("ประชาสัมพันธ์", "pra-cha-sam-phan", "Öffentlichkeitsarbeit", "Public Relations"),
    ("โฆษณา", "kho-sa-na", "Werben", "Advertise"),
    ("ตลาด", "ta-lat", "Markt", "Market"),
    ("การบริโภค", "kan-bo-ri-phok", "Konsum", "Consumption"),
    ("อุปสงค์", "up-pa-song", "Nachfrage", "Demand"),
    ("อุปทาน", "up-pa-than", "Angebot", "Supply"),
    ("เงินเฟ้อ", "ngoen-foe", "Inflation", "Inflation"),
    ("เงินฝืด", "ngoen-fuet", "Deflation", "Deflation"),
    ("รายได้", "rai-dai", "Einkommen", "Income"),
    ("รายจ่าย", "rai-jai", "Ausgaben", "Expenditure"),
    ("กำไร", "kam-rai", "Gewinn", "Profit"),
    ("ขาดทุน", "khat-thun", "Verlust", "Loss"),
    ("หนี้สิน", "nee-sin", "Verbindlichkeit", "Liability"),
    ("ทรัพย์สิน", "sap-sin", "Vermögen", "Asset"),
    ("มรดก", "mo-ra-dok", "Erbe", "Inheritance"),
    ("ภาษี", "pha-see", "Steuer", "Tax"),
    ("ศุลกากร", "sun-la-ka-kon", "Zoll", "Customs"),
    ("งบประมาณ", "ngop-pra-man", "Budget", "Budget"),
    ("โครงการ", "khrong-kan", "Projekt", "Project"),
    ("แผนงาน", "phaen-ngan", "Arbeitsplan", "Work plan"),
    ("นโยบาย", "na-yo-bai", "Politik", "Policy"),
    ("วัตถุประสงค์", "wat-thu-pra-song", "Objektiv", "Objective"),
    ("เป้าหมาย", "pao-mai", "Ziel", "Target"),
    ("กลยุทธ์", "kon-la-yut", "Strategie", "Strategy"),
    ("ยุทธศาสตร์", "yut-tha-sat", "Strategie (Militär/Groß)", "Grand Strategy"),
    ("ปฏิบัติการ", "pa-ti-bat-kan", "Operation", "Operation"),
    ("ภารกิจ", "pha-ra-kit", "Mission", "Mission"),
    ("วิสัยทัศน์", "wi-sai-that", "Vision", "Vision"),
    ("ผู้นำ", "phu-nam", "Anführer", "Leader"),
    ("บริหาร", "bo-ri-han", "Verwalten", "Administer"),
    ("จัดการ", "jat-kan", "Managen", "Manage"),
    ("ควบคุม", "khuap-khum", "Kontrollieren", "Control"),
    ("ดูแล", "du-lae", "Beaufsichtigen", "Supervise"),
    ("ตรวจสอบ", "truat-sop", "Überprüfen", "Inspect"),
    ("ติดตาม", "tit-tam", "Verfolgen", "Track"),
    ("รายงาน", "rai-ngan", "Berichten", "Report"),
    ("นำเสนอ", "nam-sa-noe", "Präsentieren", "Present"),
    ("อภิปราย", "a-phi-prai", "Diskutieren (Debatte)", "Debate"),
    ("สัมมนา", "sam-ma-na", "Seminar", "Seminar"),
    ("ประชุม", "pra-chum", "Treffen", "Meeting"),
    ("มติ", "ma-ti", "Resolution", "Resolution"),
    ("ข้อสรุป", "kho-sa-rup", "Fazit", "Conclusion"),
    ("คำตัดสิน", "kham-tat-sin", "Urteil", "Verdict"),
    ("คำสั่ง", "kham-sang", "Befehl", "Order"),
    ("ประกาศ", "pra-kat", "Ankündigung", "Announcement"),
    ("แถลงการณ์", "tha-laeng-kan", "Statement", "Statement"),
    ("สัญญา", "san-ya", "Vertrag", "Contract"),
    ("ข้อตกลง", "kho-tok-long", "Abkommen", "Agreement")
]

# Combine all lists
all_vocab_sets = [
    ("Everyday", everyday_list),
    ("A1", a1_list),
    ("A2", a2_list),
    ("B1", b1_list),
    ("B2", b2_list),
    ("C1", c1_list),
    ("C2", c2_list)
]

# Generate JS file content
js_content = "const newVocab = [\n"
word_id = 2000

for level, word_list in all_vocab_sets:
    for thai, translit, german, english in word_list:
        entry = {
            "id": word_id,
            "level": level,
            "thai": thai,
            "transliteration": translit,
            "german": german,
            "english": english
        }
        js_content += "    " + json.dumps(entry, ensure_ascii=False) + ",\n"
        word_id += 1

js_content = js_content.rstrip(",\n") + "\n];\n\n// Append to main list\nif (typeof vocabList !== 'undefined') {\n    vocabList = vocabList.concat(newVocab);\n}\n"

with open("vocab_expansion.js", "w", encoding="utf-8") as f:
    f.write(js_content)

print(f"Generated {word_id - 2000} vocab entries in vocab_expansion.js")

