const UI_TEXTS = {
    de: {
        title: "Thai Lernkarten",
        mode_label: "Lernrichtung",
        mode_th_de: "🇹🇭 → 🇩🇪",
        mode_de_th: "🇩🇪 → 🇹🇭",
        mode_th_en: "🇹🇭 → 🇬🇧",
        mode_en_th: "🇬🇧 → 🇹🇭",
        mode_review: "Fehler wiederholen",
        level_label: "Schwierigkeitsgrad",
        level_all: "Alle Levels",
        level_a1: "A1 (Anfänger)",
        level_a2: "A2 (Grundlagen)",
        level_everyday: "Alltag",
        level_numbers: "Zahlen (1-100)",
        level_b1: "B1 (Fortgeschritten)",
        level_b2: "B2 (Selbstständig)",
        level_c1: "C1 (Fachkundig)",
        level_c2: "C2 (Experte)",
        type_label: "Modus",
        type_flashcards: "Karteikarten",
        type_sentence: "Sätze",
        type_quiz: "Quiz (Multiple Choice)",
        stats_btn: "Statistik ansehen",
        stats_header: "Gesamtfortschritt",
        stats_back: "Zurück zum Menü",
        start_btn: "Starten",
        flip_hint: "Klicken zum Umdrehen",
        btn_wrong: "Falsch",
        btn_correct: "Richtig",
        btn_next: "Weiter",
        btn_menu: "Menü",
        stats_correct: "Richtig:",
        stats_wrong: "Falsch:",
        stats_remaining: "Verbleibend:",
        completed_title: "Glückwunsch!",
        completed_msg: "Du hast alle Karten gelernt.",
        restart_btn: "Neustart",
        settings_lang: "Sprache",
        reset_progress: "Fortschritt zurücksetzen",
        correct_count: "Korrekte Antworten",
        wrong_count: "Falsche Antworten"
    },
    th: {
        title: "แฟลชคาร์ดภาษาไทย",
        mode_label: "โหมดการเรียนรู้",
        mode_th_de: "🇹🇭 → 🇩🇪",
        mode_de_th: "🇩🇪 → 🇹🇭",
        mode_th_en: "🇹🇭 → 🇬🇧",
        mode_en_th: "🇬🇧 → 🇹🇭",
        mode_review: "ทบทวนข้อผิดพลาด",
        level_label: "ระดับความยาก",
        level_all: "ทุกระดับ",
        level_a1: "A1 (ระดับต้น)",
        level_a2: "A2 (พื้นฐาน)",
        level_everyday: "ชีวิตประจำวัน",
        level_numbers: "ตัวเลข (1-100)",
        level_b1: "B1 (ระดับกลาง)",
        level_b2: "B2 (ระดับกลางสูง)",
        level_c1: "C1 (ระดับสูง)",
        level_c2: "C2 (ระดับเชี่ยวชาญ)",
        type_label: "โหมด",
        type_flashcards: "แฟลชคาร์ด",
        type_sentence: "ประโยค",
        type_quiz: "แบบทดสอบ",
        stats_btn: "ดูสถิติ",
        stats_header: "ความคืบหน้า",
        stats_back: "กลับเมนูหลัก",
        start_btn: "เริ่ม",
        flip_hint: "คลิกเพื่อพลิก",
        btn_wrong: "ไม่ถูกต้อง",
        btn_correct: "ถูกต้อง",
        btn_next: "ถัดไป",
        btn_menu: "เมนู",
        stats_correct: "ถูกต้อง:",
        stats_wrong: "ผิด:",
        stats_remaining: "เหลือ:",
        completed_title: "ยินดีด้วย!",
        completed_msg: "คุณเรียนครบทุกใบแล้ว",
        restart_btn: "เริ่มใหม่",
        settings_lang: "ภาษา",
        reset_progress: "รีเซ็ตความคืบหน้า",
        correct_count: "คำตอบที่ถูกต้อง",
        wrong_count: "คำตอบที่ผิด"
    }
};
